### ISSUE TITLE
Glassmorphism UI Design 

### ISSUE THREAD

**Issue by awantika10** [awantika10/Desgen#1]
**Idea :** We are probably planning to design innovative ideas which solve our day- to day problems. Any such problem which we face can be well - explained through **Glassmorphism UI**. Contributours are welcomed to propose their ideas.

**Requirements :** We will be working on any one such real-world problems and will be creating wireframes, low - high fidelity mockups, prototypes etc.

**Software Requirements:** The idea will be designed from scratch with any designing software such as Figma, Adobe XD, Illustrator,Photoshop etc for scratch.

Example :  A concept mental wellness app for improving mental health and mood

![43402db393ab979e192d80546581dc81](https://user-images.githubusercontent.com/71998138/109604391-745ccd00-7b49-11eb-9b21-387c65407e8d.png)

**Comment by thaditi** [comment]
Hey @awantika10.  I would like to contribute to this as part of GSSoc'21.

**Comment by awantika10** [comment]
Hey @thaditi Kindly join our discord server for further discussion :)

**Comment by thaditi** [comment]
Sure. Thanks

**Comment by aritrochakraborty29** [comment]
Hey.. @awantika10  ..I would like to contribute in this part...

**Comment by awantika10** [comment]
Hey @aritrochakraborty29 Kindly join the discord server for further discussion :)

**Comment by Dev-anuj** [comment]
joined discord, when it will start!

**Comment by awantika10** [comment]
Kindly ask your queries in discord channnel

**Comment by vkassingh** [comment]
I would like to work on this issue by designing an app for covid19 vaccine registration using glassmorphism.
 please assign it to me.

**Comment by awantika10** [comment]
@vkassingh Please update your idea here

**Comment by kunal299** [comment]
@awantika10 I would also like to work on this issue with @vkassingh. Could you please assign me also?

**Comment by vkassingh** [comment]
Here is the user flow of my idea. 
https://www.figma.com/file/7oCF0yFoEK6ZCis9hbhe7O/Vaccine-Registration-app?node-id=0%3A1

**Comment by VishalPatil18** [comment]
Hey, @awantika10 can you describe the prime objective? As in do we just have to make the design or do we also have to code it in HTML CSS JS? Also would appreciate contributing to this project under GSSoC'21. Thanks!

**Comment by awantika10** [comment]
@SpecTEviL We are probably planning to design innovative ideas which solve our day- to day problems. Any such problem which we face can be well - explained through UI. 
For example : Designing a application that makes it safe to find the ideal roommate in a new city or designing a file management system accessed and organised through Virtual Reality, etc. We will be designing such problems using glassmorphism, neumorphism, etc. We won't be working on the code, just the design and prototype.

**Comment by VishalPatil18** [comment]
Got it. Thanks! I Will work on this if you can assign it to me. Or else I'll make a PR once I'm done. Whichever is preferable to you guys. Thanks.

**Comment by awantika10** [comment]
@vkassingh @kunal299  Please update with your wireframes

**Comment by kunal299** [comment]
one frame is left. We will add it. 
![image](https://user-images.githubusercontent.com/71486434/110595715-612eaa80-81a4-11eb-86e3-860553eab432.png)

**Comment by kunal299** [comment]
@awantika10 I have shared the wireframes. Check it out.

**Comment by weebo-ary** [comment]
Ask in the conversation before making any PR.

**Comment by vkassingh** [comment]
@SHITIZ-AGGARWAL @awantika10 
We have made these 4 screens. But it is looking somewhat empty. Is there any way i can improve the design screen?

![2nd](https://user-images.githubusercontent.com/42089632/110746953-a0700080-8263-11eb-803d-cb1254fb166a.JPG)

**Comment by weebo-ary** [comment]
Announcement Regarding PR -
Before Making any Pull Request Kindly Ask in The Conversation because it can conflict our master branch. 
You can ask to @awantika10 , @SHITIZ-AGGARWAL , @weebo-ary before making any PR weather on GitHub or Discord (On any Server).

**Comment by kunal299** [comment]
@awantika10 @SHITIZ-AGGARWAL @weebo-ary Please review this design made by me and @vkassingh. 
![image](https://user-images.githubusercontent.com/71486434/111028121-a4924e80-841a-11eb-96c2-c79dbfa6f505.png)

**Comment by SKV-programmer** [comment]
@awantika10 I would like to contribute in this part....

**Comment by awantika10** [comment]
@vkassingh @kunal299 Your designs need to be improved, please refer to the resources given in discord channel

**Comment by awantika10** [comment]
> @vkassingh @kunal299 Your designs need to be improved, please refer to the resources given in discord channel

Update?

**Comment by kunal299** [comment]
@awantika10 We both have done a little bit of update. We will complete it asap.
![image](https://user-images.githubusercontent.com/71486434/112302186-cd3f0180-8cc0-11eb-99d7-36e5a1742bec.png)

**Comment by SHITIZ-AGGARWAL** [comment]
@kunal299 you can also try different colours
