### ISSUE TITLE
Revamp the footer section

### ISSUE THREAD

**Issue by Smriti129** [awantika10/Desgen#100]
![Screenshot (32)](https://user-images.githubusercontent.com/76429418/111910180-54ecfc00-8a86-11eb-9d31-2eb2a6fcae06.png)
I want to add changes in the format and styling of footer section, so that it looks attractive. 
I'm a participant of GSSOC'21. Please assign me this issue.

**Comment by SHITIZ-AGGARWAL** [comment]
@Smriti129 This is dribbble not desgen . Dribbble is the platform where we have posted our designs.
