### ISSUE TITLE
Feat: Logo_for_Desgen

### ISSUE THREAD

**Issue by weebo-ary** [awantika10/Desgen#102]
**What is your feature request related to ?**

- [x] Desgen Website
- [x] Designing
- [ ] Documentation
- [ ] Others[please specify like testing, code etc]

**Description**

Make a logo for Desgen website which should be :

1. Attractive.
2. Colorful.
3. Related to our Theme.

**For any Doubts regarding this issue you can ask in Discord Server !!**

**Comment by Avnish5** [comment]
Kindly assign this task to me under GSSOC 2021.

**Comment by weebo-ary** [comment]
Do you have any prior knowledge regarding Logo Making ?? @Avnish5

**Comment by Avnish5** [comment]
> Do you have any prior knowledge regarding Logo Making ?? @Avnish5
No sir but i have creative mind.So i will try my best to create the logo.

**Comment by weebo-ary** [comment]
This is open for all you can start your work......

**Comment by ambivert-sam** [comment]
Hey! @weebo-ary I want to contribute on this , will you please assign it to me?

**Comment by unshDee** [comment]
Can the logo have some kind of animation in it??

**Comment by ayu222220** [comment]
Cann I work on the design. I have asked you on the discord regarding this. From GSSOC'21. Would love to work on it. Can you assign me?

**Comment by SHITIZ-AGGARWAL** [comment]
@ambivert-sam @ayu222220 No need of getting assigned . You can start working on the issue, after your work is complete show your logo in the comments

**Comment by SHITIZ-AGGARWAL** [comment]
@unshDee We have to use this logo for various platforms so I don't think animation will be feasible

**Comment by Shubhrima** [comment]
![desgen](https://user-images.githubusercontent.com/68013183/112466808-435c6a80-8d8c-11eb-9042-f72092a74550.jpg)


can someone please review this!?

**Comment by jhasuraj01** [comment]
My Logo Submission:

![image](https://user-images.githubusercontent.com/44930179/112501771-85e36e80-8daf-11eb-8f6a-a03b1e8cc1e5.png)

**Comment by sowmiyeh** [comment]
###  Logo Submission
Name : Sowmiya V
Discord name :  Sowmiya V#1169

![Desgen Logo](https://user-images.githubusercontent.com/74345706/112511739-b67bd600-8db8-11eb-99c3-50c98f26fa1e.png)

**Comment by SHITIZ-AGGARWAL** [comment]
> ### Logo Submission
> Name : Sowmiya V
> Discord name : Sowmiya V#1169
> 
> ![Desgen Logo](https://user-images.githubusercontent.com/74345706/112511739-b67bd600-8db8-11eb-99c3-50c98f26fa1e.png)

@sowmiya-venkatesan also add the previous logo you made , the one with different colour scheme

**Comment by sowmiya-venkatesan** [comment]
> > ### Logo Submission
> > Name : Sowmiya V
> > Discord name : Sowmiya V#1169
> > ![Desgen Logo](https://user-images.githubusercontent.com/74345706/112511739-b67bd600-8db8-11eb-99c3-50c98f26fa1e.png)
> 
> @sowmiya-venkatesan also add the previous logo you made , the one with different colour scheme

![Desgen website (1)](https://user-images.githubusercontent.com/74345706/112512345-4caffc00-8db9-11eb-9b3b-a7f749386c43.png)

**Comment by sowmiya-venkatesan** [comment]
> > ### Logo Submission
> > Name : Sowmiya V
> > Discord name : Sowmiya V#1169
> > ![Desgen Logo](https://user-images.githubusercontent.com/74345706/112511739-b67bd600-8db8-11eb-99c3-50c98f26fa1e.png)
> 
> @sowmiya-venkatesan also add the previous logo you made , the one with different colour scheme

![Uploading Desgen website (2).png…]()

**Comment by sowmiyeh** [comment]
> > ### Logo Submission
> > Name : Sowmiya V
> > Discord name : Sowmiya V#1169
> > ![Desgen Logo](https://user-images.githubusercontent.com/74345706/112511739-b67bd600-8db8-11eb-99c3-50c98f26fa1e.png)
> 
> @sowmiya-venkatesan also add the previous logo you made , the one with different colour scheme

![Desgen website (2)](https://user-images.githubusercontent.com/74345706/112512807-b4fedd80-8db9-11eb-86f8-2667b469ba2e.png)

**Comment by Bhawna147** [comment]
![4600_Gallery.jpg](https://user-images.githubusercontent.com/79100530/112512861-c647ea00-8db9-11eb-84d5-157b49424fd4.jpg)

My logo design
Name - Bhawna khatri
Discord I'd - Bhawna#9241

**Comment by ambivert-sam** [comment]
hey @SHITIZ-AGGARWAL @weebo-ary please review it 

![brand_logo](https://user-images.githubusercontent.com/74984661/112519684-9d772300-8dc0-11eb-982c-7eba073b1dc0.png)

Desgen - logo 
Name - Samruddhi Wasu
Discord - Samruddhi(P) #4035

**Comment by vaibhavpathak999** [comment]
Name: Vaibhav Pathak
Discord: Vaibhav(P)#9231

![Desgen Logo D New](https://user-images.githubusercontent.com/51280899/112575627-ac88c000-8e16-11eb-93a8-cac15a5b9018.png)

**Comment by deepti262002** [comment]
![Medium Violet Square Real Estate Logo](https://user-images.githubusercontent.com/79099303/112591516-78b79580-8e2a-11eb-8b11-c66a974f7ab8.png)

**Comment by ayu222220** [comment]
Name: Ayushi Singh

![WhatsApp Image 2021-03-24 at 2 16 57 PM (1)](https://user-images.githubusercontent.com/65357585/112610037-43b73d00-8e42-11eb-8116-b200ec640c76.jpg)

**Comment by ayu222220** [comment]
Name: Ayushi Singh

![DESGEN](https://user-images.githubusercontent.com/65357585/112610193-6e08fa80-8e42-11eb-82ef-5968252598b1.png)

**Comment by Prathana1** [comment]
hey, can i contribute on this

**Comment by Prathana1** [comment]
![desgen jpeg](https://user-images.githubusercontent.com/66274793/112636758-85a4ab00-8e63-11eb-9caa-069ec9d9a58a.jpg)

**Comment by SAHU-01** [comment]
![image](https://user-images.githubusercontent.com/71656941/112640883-ce5e6300-8e67-11eb-965f-7b7b5388ec52.png)

**Comment by ANSHIKA1806** [comment]
![logo_desgen](https://user-images.githubusercontent.com/71966377/112643611-8db41900-8e6a-11eb-9da2-dcef60c367d7.jpeg)
@SHITIZ-AGGARWAL @ayu222220 @weebo-ary @ShauryaBhandari  I am Anshika, a GSSoC participant and I had contributed in this project previously on README file. I would love to contribute in this issue also. Please review my logo and let know if anything better you expect.

**Comment by aman339** [comment]
Please Assign me this issue @SHITIZ-AGGARWAL @weebo-ary @ShauryaBhandari . I want to contribute on this issue. its my first issue in GSSoC@21 where i want to add my contribution in this .

**Comment by aman339** [comment]
Desgen Logo 
Name: Aman Kumar Choudhary
Discord: Aman Kumar Choudhary(P)#4888
@SHITIZ-AGGARWAL @weebo-ary @ShauryaBhandari  I created this logo please review it and let me know if i can do some changes in this.
![esgen (1)](https://user-images.githubusercontent.com/66405145/112714442-67d95380-8f00-11eb-94b3-a2d9c2f1e6c5.png)

**Comment by rakupcode** [comment]
![desgen Logo](https://user-images.githubusercontent.com/79015142/112743887-ccf08000-8fb8-11eb-87ee-ab69c0be2890.png)
Did some fun in paint 3D.
I am a novice in logo making.

**Comment by Jatinchourasia** [comment]
![Frame 3](https://user-images.githubusercontent.com/69300666/112849363-d7b12080-905d-11eb-8431-efb2666e8da2.jpg)
name: jatin chourasia
discord: Jatin(P)#0047

**Comment by Vishnurr2k01** [comment]
please assign me to this project.I have created a logo

**Comment by Vishnurr2k01** [comment]
Please assign this project to me.I have created one

**Comment by Vishnurr2k01** [comment]
Please Assign me this issue. I have created a logo.

**Comment by Vishnurr2k01** [comment]
![DESGEN LOGO](https://user-images.githubusercontent.com/72376269/113505586-5d046b80-955d-11eb-8230-7ea29af19df2.jpg)
name : Vishnu R Potti
discord : vishnurr#1245

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> ![desgen](https://user-images.githubusercontent.com/68013183/112466808-435c6a80-8d8c-11eb-9042-f72092a74550.jpg)
> 
> can someone please review this!?

Why is D included inside if we are getting BIG D

**Comment by rohan-kulkarni-25** [comment]
@SHITIZ-AGGARWAL Is this still open ? I will like to work on it !

**Comment by ambivert-sam** [comment]
![Desgen 1](https://user-images.githubusercontent.com/74984661/114276826-fe039280-9a45-11eb-836a-a9f64d88a9c9.png)
![Desgen 2](https://user-images.githubusercontent.com/74984661/114276833-03f97380-9a46-11eb-90fd-07b5ce8487fe.png)
 
I came up with two new design @SHITIZ-AGGARWAL @weebo-ary @ayu222220 please review it

Desgen - logo
Name - Samruddhi Wasu
Discord - Samruddhi(P) #4035

**Comment by ambivert-sam** [comment]
![White with Colorful Triangles Internet Logo](https://user-images.githubusercontent.com/74984661/114276942-8e41d780-9a46-11eb-99ab-14924dace2a0.png)


![Desgen 2](https://user-images.githubusercontent.com/74984661/114276950-94d04f00-9a46-11eb-9702-fcda518eddfc.png)

I came up with two new design @SHITIZ-AGGARWAL @ayu222220  @weebo-ary please review it

Desgen - logo
Name - Samruddhi Wasu
Discord - Samruddhi(P) #4035

**Comment by SHITIZ-AGGARWAL** [comment]
@vaibhavpathak999 @ambivert-sam @sowmiya-venkatesan @aman339 @rakup444 you all can create a PR for this issue. Add all your logos in the [Desgen_Logo](https://github.com/awantika10/Desgen/tree/gssoc/Designs/Desgen_Logo) folder (.png or .svg only) and keep your name as the file name. 
For multiple logos you can add like 
name_1.svg
name_2.svg

**Comment by ambivert-sam** [comment]
> @vaibhavpathak999 @ambivert-sam @sowmiya-venkatesan @aman339 @rakup444 you all can create a PR for this issue. Add all your logos in the [Desgen_Logo](https://github.com/awantika10/Desgen/tree/gssoc/Designs/Desgen_Logo) folder (.png or .svg only) and keep your name as the file name.
> For multiple logos you can add like
> name_1.svg
> name_2.svg

okay

**Comment by aman339** [comment]
Okay sir🤗 work in progress

**Comment by rakupcode** [comment]
> @vaibhavpathak999 @ambivert-sam @sowmiya-venkatesan @aman339 @rakup444 you all can create a PR for this issue. Add all your logos in the [Desgen_Logo](https://github.com/awantika10/Desgen/tree/gssoc/Designs/Desgen_Logo) folder (.png or .svg only) and keep your name as the file name.
> For multiple logos you can add like
> name_1.svg
> name_2.svg

Sorry, I did not add the following:
Name: Raushan Kumar
Discord: Raushan Kumar#9085
And, I will make the PR.
Thank you.

**Comment by SHITIZ-AGGARWAL** [comment]
> > @vaibhavpathak999 @ambivert-sam @sowmiya-venkatesan @aman339 @rakup444 you all can create a PR for this issue. Add all your logos in the [Desgen_Logo](https://github.com/awantika10/Desgen/tree/gssoc/Designs/Desgen_Logo) folder (.png or .svg only) and keep your name as the file name.
> > For multiple logos you can add like
> > name_1.svg
> > name_2.svg
> 
> Sorry, I did not add the following:
> Name: Raushan Kumar
> Discord: Raushan Kumar#9085
> And, I will make the PR.
> Thank you.

No problem
