### ISSUE TITLE
Enhancement the UI of the main website [GSSoC'21]

### ISSUE THREAD

**Issue by vineetsingh0809** [awantika10/Desgen#108]
## Expected Behavior

I went through the main website and I felt that I can enhance the UI of the website. By this, it will look much better.

## Actual Behavior

I want to change some colors of the website so it will look nicer. And want to add some additional features in the buttons and posted posts.

So could you assign this issue to me? I had already cloned this on my local system,
Thank You

**Comment by SHITIZ-AGGARWAL** [comment]
The website is not made yet, you saw the dribble profile. We will be raising issues for website development soon you can contribute then . Closing the issue for now
