### ISSUE TITLE
Want to add hover effect in the website.

### ISSUE THREAD

**Issue by Ritika539** [awantika10/Desgen#114]
**What is your feature request related to ?**

- [x] Desgen Website
- [ ] Designing
- [ ] Documentation
- [ ] Others[please specify like testing, code etc]

**Description**
With the help of CSS, I want to add a hover effect in the website. This effect will make the website look good.

**Comment by SHITIZ-AGGARWAL** [comment]
@Ritika539 the website is not ready yet, the one which you are referring is our dribble profile.
