### ISSUE TITLE
Feat: Add social apps to left of the screen

### ISSUE THREAD

**Issue by ShrutiOmer** [awantika10/Desgen#123]
**What is your feature request related to ?**

- [x] Desgen Website
- [ ] Designing
- [ ] Documentation
- [ ] Others[please specify like testing, code etc]

**Description**
What is your feature request ? 
Instead of having social apps icon in footer, we can add them to left of the website. They will scale out when user hover

Please assign this issue to me.

**Comment by SHITIZ-AGGARWAL** [comment]
@ShrutiOmer the one which you are talking about is our dribbble profile. The website is under development
