### ISSUE TITLE
Bug: Small typo error in feature issue template

### ISSUE THREAD

**Issue by ShrutiOmer** [awantika10/Desgen#124]
## Expected Behavior
"Description" is spelled as "Describtion"

**Comment by SHITIZ-AGGARWAL** [comment]
@ShrutiOmer You can go ahead , please check  README.md and CONTRIBUTING.md  also and correct them

**Comment by SHITIZ-AGGARWAL** [comment]
@ShrutiOmer Please give an update regarding this
