### ISSUE TITLE
Feat: Customize you Smoothie App

### ISSUE THREAD

**Issue by anhushree** [awantika10/Desgen#127]
**What is your feature request related to ?**

- [ ] Desgen Website
- [x] Designing
- [x] Documentation
- [ ] Others[please specify like testing, code etc]

**Description**
What is your feature request? 
A Smoothie App named Smoogles allows the customer to order any smoothie that they want from an existing list or customize and make their own smoothie.
Uses latest design tech like Glassmorphism, Neumorphism, etc.
Made by Design software like Figma, AdobeXd, etc.

**Describe the solution you'd like**

- People can order Smoothie from a list
- They can also use a feature called SmoothieMaker where they select the ingredients for the smoothie
- Order Tracker page so that they can know when the Smoothie arrives.
- Drag and Drop feature for SmoothieMaker
- Availability of Coupons  
- Login/SignUp page

**Comment by anhushree** [comment]
@awantika10 @SHITIZ-AGGARWAL I would like to work on this issue as a GSSoC'21 participant. Kindly assign, Thank You.

**Comment by SHITIZ-AGGARWAL** [comment]
@anhushree We are not taking new designs idea right now. We want to focus on current ideas first. After finishing these ideas you can raise this issue.
