### ISSUE TITLE
Feat: Case Study For Desgen Community Website

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [awantika10/Desgen#129]
**What is your feature request related to ?**

- [x] Desgen Website
- [x] Designing
- [x] Documentation

**Description**

We are thinking of making Desgen a community platform for all the designers. 
- Designers can create an account and post their designs
- Features for community talks and meetings
- Discussion forums
- Hiring and freelance 

These are some basic features. Research and explore more features for the platform

For reference : Dribbble and Behance
But we should have features which makes our platform better and unique

**Describe the solution you'd like**

Make a case study for the platform on google Docs
Your case study should include : 

- Research
- User Flowchart
- Sketches or Wireframes
- Visual Research : Inspiration Board, Iteration, Color Palette, Typography, Icons & Illustrations, Micro-Interactions and Animation
- Final Design

[case study example](https://uxdesign.cc/ui-ux-case-study-a-step-by-step-guide-to-the-process-of-designing-a-pet-diet-app-d635b911b648)

**Additional context**
This is a big issue thus we prefer if assignees work in teams

**Comment by subhasmitapradhan** [comment]
I would like to work on this. Being a frequenter of bihance and dribble I have basic idea what a user needs in the site and what could make it better and unique.

**Comment by ASLManasa** [comment]
I am a gssoc'21 participant and I would like to work on this. Thank you.

**Comment by Ritika539** [comment]
Hey @SHITIZ-AGGARWAL , 
I would like to work on this issue as a GSSoC'21 participant under the guidance of the mentor.

**Comment by anhushree** [comment]
I would like to work on this issue as a GSSoC'21 partcipant.

**Comment by SHITIZ-AGGARWAL** [comment]
@anhushree @Ritika539 @ASLManasa @subhasmitapradhan Share your thoughts for the platform [here](https://discord.com/channels/803551426009759745/821998203322630165). You can talk about 
- New features which we can implement in our platform 
- The problems people face on other similar platforms and how we can solve these problems in our platform
- How we can make our platform unique
- General problems designers face and how we can solve these problems through out platform

Based on your responses we will make teams and assign contributors

**Comment by vaibhavpathak999** [comment]
Hey @SHITIZ-AGGARWAL,
I would like to contribute to this issue.

**Comment by sardonicankita** [comment]
Hi, can I be assigned to this issue?

**Comment by subhangi2731** [comment]
@SHITIZ-AGGARWAL can u please assign this issue to me
