### ISSUE TITLE
add contributing.md

### ISSUE THREAD

**Issue by khareyash05** [awantika10/Desgen#134]
Hi I would like to create a file contributing.md and add the following -
Difference between GIT and GITHUB
How to clone,fork repository
How to create a branch and then use git push to push to repo
Create a PR
Squash commits in a single issue into one
Updating the forked and local repo as the updations are made in the upstream

**Comment by SHITIZ-AGGARWAL** [comment]
@khareyash05 please go through the repo before making an issue. We already have CONTRIBUTING.md
