### ISSUE TITLE
Feat: Navbar should be sticky

### ISSUE THREAD

**Issue by SamikshaSankar** [awantika10/Desgen#146]
**What is your feature request related to ?**
- [ ] Designing

**Description**
What is your feature request ? - Navbar sohuld be sticky. When we scroll nav bar should be present at the top.

**Describe the solution you'd like**
By using HTML, CSS, JS we can make nav to sticky.

**Comment by SHITIZ-AGGARWAL** [comment]
@SamikshaSankar 
The website is not designed yet, you can contribute in the website after the design is ready
