### ISSUE TITLE
Improvement in UI of Desgen home page

### ISSUE THREAD

**Issue by ishikajn8126** [awantika10/Desgen#148]
**What is your feature request related to ?**

- [x] Desgen Website
- [ ] Designing
- [ ] Documentation
- [ ] Others[please specify like testing, code etc]

**Description**
- Changes in colors of some elements on home page
- Increasing the prominence of pink and white color combination.

**Describe the solution you'd like**

- Follow and Recent shots buttons will look similar to sign up button and will also be given hover properties similar to it.
- All border lines will be made pink. There is a border line above footer too, that will also be made pink.
- Search icon and dribble at navbar will be made pink.
-  Number of shots, collections, liked shots will also be made pink. 

**Additional context**
After proposed changes:
![image](https://user-images.githubusercontent.com/72145053/115990484-1f858200-a5e1-11eb-8ca2-e7c1f7ccd3bc.png)

Current look:
![image](https://user-images.githubusercontent.com/72145053/115990511-4774e580-a5e1-11eb-91e4-ced5b7955dfe.png)
.
.
.
I would like to work on this as GSSOC participant.
Please assign this to me.

@awantika10 @SHITIZ-AGGARWAL @ShauryaBhandari

**Comment by awantika10** [comment]
Raise an issue when website design is completed
