### ISSUE TITLE
Change the navbar to sidebar or navigation drawer

### ISSUE THREAD

**Issue by subhangi2731** [awantika10/Desgen#161]
I will change the navbar to sidebar and make it more enhancing

**Comment by subhangi2731** [comment]
@awantika10 @SHITIZ-AGGARWAL please assign this issue to me

**Comment by subhangi2731** [comment]
@awantika10 @SHITIZ-AGGARWAL please assign me so that i can start working

**Comment by SHITIZ-AGGARWAL** [comment]
@subhangi2731 The one which you are referring is our dribbble profile. We are working on building our website.
