### ISSUE TITLE
online shopping app UI design (gssoc21)

### ISSUE THREAD

**Issue by swathika1** [awantika10/Desgen#162]
**What is your feature request related to ?**

- [x] Desgen Website
- [x] New design
- [x] Gssoc21 

**Description**
An eye catchy design for online shopping app that sells everyday needs and fashion apparel in figma.

**Comment by ishitakapoor26** [comment]
Hi @swathika1 can i work on this issue?

**Comment by swathika1** [comment]
Im waiting for @awantika10 to assign this issue to me.
