### ISSUE TITLE
Want_to_add_design

### ISSUE THREAD

**Issue by Anubhavdevv** [awantika10/Desgen#169]
**What is your feature request related to ?**

- [ ] Desgen Website
- [x] Designing
- [ ] Documentation
- [ ] Others[please specify like testing, code etc]

**Description**
Want to add my design which I created through Adobe Photoshop

**Describe the solution you'd like**
Add a design to the repo

@awantika10 Please assign this issue to me

**Comment by SHITIZ-AGGARWAL** [comment]
Please share the ss of design

**Comment by SHITIZ-AGGARWAL** [comment]
@anubhav201241 Check out #170
