### ISSUE TITLE
Feat: Want to add your designs ?

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [awantika10/Desgen#170]
**This issue is related to**

- [ ] Desgen Website
- [x] Designing
- [x] Documentation
- [ ] Others[please specify like testing, code etc]

**Description**
If you want to contribute your designs in this project, first comment in the issue telling about
-  What particular design you want to contribute
-  What technologies you used/will be using while making this design
-  Description of the design
-  A link to your design if it is already made (if you have pictures or ss, you can upload it on your drive and share that link )

`Please do not raise PRs or issues, till your design get's approved`

**Additional context**
If you have an idea you want to work on with designing, you can also share that . For more information join discord channel 
https://discord.gg/RaCkpwzv

**Comment by Vedant-Jayesh-Oza** [comment]
@SHITIZ-AGGARWAL what kind of designs we can add ? Like do we have to add the jpeg or png format of design ?

**Comment by SHITIZ-AGGARWAL** [comment]
@Vedant-Jayesh-Oza you have to add designs of applications or websites with unique ideas.
Before making a PR, get your designs reviewed on discord. After it gets reviewed you have to create a folder and put all the design screens in .png or .svg format

**Comment by Vedant-Jayesh-Oza** [comment]
@SHITIZ-AGGARWAL I have sent you the Idea in Slack DM is it OK?
