### ISSUE TITLE
Feat: Zoom hover effect on Cards

### ISSUE THREAD

**Issue by SamikshaSankar** [awantika10/Desgen#171]
**What is your feature request related to ?**

- [x] Desgen Website
- [x] Designing
- [ ] Documentation
- [ ] Others[please specify like testing, code etc]

What is your feature request ? (A description of the feature. Write about the problem or idea you want to refer in this issue.)
Add zoom effect on cards

@awantika10 please assign me

**Comment by RakeshCharpe** [comment]
can I work on this issue?

**Comment by supzi-del** [comment]
Please assign this to me under LGMSOC

**Comment by aktamoli0910** [comment]
Hi, I would like to work on this issue under LGM SOC'21. Thank You.

**Comment by jayant766** [comment]
Please assign me this issue under LGMSOC'21

**Comment by Devansh2000Shaw** [comment]
I would like to contribute on this under LGM SOC'21. Please assign me.

**Comment by jwalapc** [comment]
Hi, I would like to work on this issue under LGM SOC'21. Thank You.

**Comment by prads46** [comment]
Hi, I would like to work on this issue under LGM SOC'21. Thank You.

**Comment by varshitha1707** [comment]
Hey! I would like to work on this issue as well as add a slight colour change with the zoom effect on hover.
Please assign me this issue under LGMSOC'21
