### ISSUE TITLE
Feat: Night MOde

### ISSUE THREAD

**Issue by SanjeevKumar22** [awantika10/Desgen#172]
**What is your feature request related to ?**

- [] Desgen Website
- [x] Designing
- [ ] Documentation
- [ ] Others[please specify like testing, code etc]

**Description**
What is your feature request ? (A description of the feature. Write about the problem or idea you want to refer in this issue.)
DArk Mode
**Describe the solution you'd like**
A description of the solution you would suggest if any. (Any suggestions for issue solving)

**Additional context**

**Comment by Devansh2000Shaw** [comment]
Please assign me this under LGM SOC'21. Thank you.

**Comment by tjanhvi** [comment]
I would like to do this part. I will give a button having an indication to change the mode as change it to dark mode.
![image](https://user-images.githubusercontent.com/78703730/122383134-2e0c6c00-cf88-11eb-93b2-ac713d8c9987.png)
Like this !!!!!
I want to try this.......

**Comment by SHITIZ-AGGARWAL** [comment]
Please give a proper description for the issue. You can discuss more about this on the discord server with maintainers and then raise an issue
