### ISSUE TITLE
Feat: Add LGM-SOC'21 score card in readme.md

### ISSUE THREAD

**Issue by ishitakapoor26** [awantika10/Desgen#173]
**What is your feature request related to ?**

- [ ] Desgen Website
- [ ] Designing
- [x] Documentation
- [ ] Others[please specify like testing, code etc]

*Add LGM-SOC'21 score card in readme.md

**Comment by ishitakapoor26** [comment]
@awantika10 @SHITIZ-AGGARWAL pls assign me this issue.

**Comment by SHITIZ-AGGARWAL** [comment]
@ishitakapoor26 There is no need for a score card in the readme
