### ISSUE TITLE
Feat: add more badges and move them to the top

### ISSUE THREAD

**Issue by Umesh-01** [awantika10/Desgen#175]
**What is your feature request related to ?**

- [ ] Desgen Website
- [ ] Designing
- [x] Documentation
- [ ] Others[please specify like testing, code etc]

**Description**
I think badges should be at the top of README.md file. Here (see the image below) they are not looking good.

![image](https://user-images.githubusercontent.com/83420185/122443370-261aef00-cfbd-11eb-8255-8021a6afc287.png)

**Describe the solution you'd like**
I will move them to the top and also will add some more badges so that the README.md file will look more interactive and awesome. 

**Additional context**
Since these badges at the top of readme.md file will be colorful and more attractive than the text, the user will like it and it will also help them to navigate to different sections/ webpages like PRs, issues, contributors, etc.

**Comment by Umesh-01** [comment]
@awantika10 Should I do these changes??

**Comment by Umesh-01** [comment]
@awantika10 Should I work on this issue??

**Comment by aviral14112001** [comment]
Assign me this task I would like to work on this under "LGM SoC 21"

**Comment by awantika10** [comment]
> @awantika10 Should I work on this issue??

Yeah you can
