### ISSUE TITLE
Feat: Make scrollbar customizable and colorful

### ISSUE THREAD

**Issue by ROHAN842** [awantika10/Desgen#178]
**Description**
I would like to make the scrollbar colorful with help of animations.

Can I work on this issue ??

Could you please assign this issue to me under LGMSOC?

**Additional context**
![image](https://user-images.githubusercontent.com/61961107/123839372-abda5b00-d92a-11eb-8233-a9d9ed643205.png)

**Comment by padmajabhol** [comment]
Interested. Can you assign this to me?
