### ISSUE TITLE
Neumorphism UI Design

### ISSUE THREAD

**Issue by awantika10** [awantika10/Desgen#2]
**Idea :** We are probably planning to design innovative ideas which solve our day- to day problems. Any such problem which we face can be well - explained through **Neumorphism UI**. Contributours are welcomed to propose their ideas.

**Requirements :** We will be working on any one such real-world problems and will be creating wireframes, low - high fidelity mockups, prototypes etc.

**Software Requirements:** The idea will be designed from scratch with any designing software such as Figma, Adobe XD, Illustrator,Photoshop etc.

Example:  A plant care mobile app concept that you can use to set up a schedule of your plant care activities (such as watering 
 the plant). You can find out more information about plants and buy plants. A unique feature is that you can even take a photo of your plant and the app will help you find solutions to your plant-related apps.

https://user-images.githubusercontent.com/71998138/109603103-660db180-7b47-11eb-8245-0cc491ffa080.mp4

**Comment by kunal299** [comment]
@awantika10 Hi, I am new here. I read the overview of your project and would love to contribute to this project. Could you please provide me more details about the app/website that we are trying to create and what services do the app provides. For some context regarding me : I have been exploring neumorphism and I am fascinated by it.

**Comment by awantika10** [comment]
Hey @kunal299 kindly join our discord channel for further discussion :)

**Comment by SaraLatif99** [comment]
Hi @awantika10  I am a GSSoc'21 participant, I am interested in this project and would love to contribute to this project, how may I proceed further? I've already joined Discord for GSSoc but I didn't find any channels? can you please guide me?
Many Thanks

**Comment by awantika10** [comment]
Hi @SaraLatif99 Kindly join our Desgen GSSOC'21 discord channel. Link : https://discord.gg/nhRVW5GXFV

**Comment by KrishSavani** [comment]
Hey! @awantika10 I would like to know more about this issue and contribute to this project.
P.S: I already joined the discord server.

**Comment by awantika10** [comment]
@KrishSavani  We will be having a meet on 28th. Please check discord announcement

**Comment by disha1202** [comment]
Hello,
I am a Gssoc participant and I would like to work on this issue.

**Comment by awantika10** [comment]
@disha1202 Kindly join the discord channel for further discussion :)

**Comment by Chadha93** [comment]
Working on Wireframes using neumorphism on this issue

**Comment by awantika10** [comment]
@Chadha93 Please update your idea here

**Comment by Chadha93** [comment]
https://www.figma.com/file/F4DecTqh8rDmUJQgntTlfQ/Medicine-Check-app-userflow?node-id=0%3A1

**Comment by micksharma** [comment]
@awantika10 I have an experience in making UI on Adobe XD. I  make it. Can you assign it to me.

**Comment by awantika10** [comment]
@micksharma I have already assigned the issue

**Comment by micksharma** [comment]
Yeah , but I also have skills to solve this issue.

**Comment by Chadha93** [comment]
![Raw userflow](https://user-images.githubusercontent.com/65453826/110426098-7c79b700-80cb-11eb-840a-d7fdb29385f2.jpg)
This is just the complete raw user flow based on this the final prototype will be made 
A pull request containing the necessary resources (Figma file) has made

**Comment by YasviPatel** [comment]
hii,@awantika10 I am participate of GSSoC'21 would like to know more about this issue and contribute to this project.

**Comment by awantika10** [comment]
@YasviPatel @Chadha93  is working on the issues. Kindly looks for other issues to contribute :)

**Comment by weebo-ary** [comment]
Ask in the conversation before making any PR.

**Comment by weebo-ary** [comment]
Announcement Regarding PR -
Before Making any Pull Request Kindly Ask in The Conversation because it can conflict our master branch. 
You can ask to @awantika10 , @SHITIZ-AGGARWAL , @weebo-ary before making any PR weather on GitHub or Discord (On any Server).
