### ISSUE TITLE
Feat: RE: Idea.md file -> Ideas Folder

### ISSUE THREAD

**Issue by soumyavemuri** [awantika10/Desgen#21]
## Maintain Ideas in a separate directory ##

- [ ] Desgen Website
- [ ] Designing
- [x] Documentation
- [ ] Others[please specify like testing, code etc]

**Description**
After going through the ideas.md template, and viewing few of the pull requests already present, I believe that with more ideas coming up, maintaining them all in one file will be hard to navigate through, as well as read. Merging will also be a bit more tedious.

**The Solution I believe in**
Instead, I'd like to work on creating a directory for the ideas. Each folder in the directory will be named after the idea, and the md of this directory will contain a navigation through these ideas; a list of the heading of these ideas. The folders contain the md file for the idea and will be stand alone files for each of these ideas. This way that one ideas.md file won't get accumulated.

If the maintainers believe this is a better alternative, I'd like to work on this under GSSoC '21 please.

**Comment by nNikita1018** [comment]
Hey, I want to contribute in this project by working with issue.
Please assign me

**Comment by SHITIZ-AGGARWAL** [comment]
@soumyavemuri let's discuss this on discord in #issue-discussion first , if required then we can tell you to raise an issue and you can work on it

**Comment by SHITIZ-AGGARWAL** [comment]
closing the issue for now
