### ISSUE TITLE
3D Animations and Illustrations

### ISSUE THREAD

**Issue by awantika10** [awantika10/Desgen#3]
Try making some amazing illustrations and animations

**Comment by Tejas-r281** [comment]
hi @awantika10  what is issue,  can you please elaborate here ?

**Comment by awantika10** [comment]
Hey @Tejas-r281 Kindly join the discord server for further communication :)

**Comment by Tejas-r281** [comment]
Link?

**Comment by awantika10** [comment]
Here it is : https://discord.gg/CQFj8AQ4vq

**Comment by Tejas-r281** [comment]
it is giving  unable to accept invite

**Comment by micksharma** [comment]
Can I work on this issue ?

**Comment by chiragagrawal9200** [comment]
I would love to work on this issue!  @awantika10 could you please assign this to me?

**Comment by SHITIZ-AGGARWAL** [comment]
@micksharma and @chiragagrawal9200 assigning the issue to you both. Please give an update of your work once in every 3 days

**Comment by chiragagrawal9200** [comment]
@awantika10 Thank you. Sure...

**Comment by sushant1824** [comment]
i m intersted can u assign me

**Comment by gritika18** [comment]
Hii @awantika10 I would like to work on this issue. Can you please assign it to me? Also it would be helpful for me if you could elaborate it here

**Comment by weebo-ary** [comment]
Ask in the conversation before making any PR.

**Comment by Yaji16** [comment]
Hey! @awantika10 does the illustrations have a specific theme? I'm interest to work on this issue. Can you please assign it to me? Please do elaborate on the specifics of this issue, it would be of great help.

**Comment by aanya-trehan** [comment]
Hi @awantika10 ! I would love to work on this issue and create illustrations. Can this be assigned to me, please?

**Comment by kanchi12P** [comment]
hey @awantika10 
I want to work on this issue.
I love animations and would like to work on them.
Please assign it to me.

**Comment by awantika10** [comment]
@micksharma @sushant1824 @Tejas-r281 @kanchi12P @gritika18 @chiragagrawal9200 This is an issue that is open to all. You can directly make a PRs as soon as you are finished which your illustrations. Also, illustrations can be of any domain. Please add your illustrations in designs folder as directed in contributing.md

**Comment by jyoti-anjaly** [comment]
Hey , I am participant in GSSOC'21. Can you please assign this to me?

**Comment by richakumari19** [comment]
Hey , I am participant in GSSOC'21. Can you please assign this to me?

**Comment by ShreyaJindal** [comment]
Where can I upload my illustrations? Do I have to make a PR?

**Comment by weebo-ary** [comment]
Announcement Regarding PR -
Before Making any Pull Request Kindly Ask in The Conversation because it can conflict our master branch. 
You can ask to @awantika10 , @SHITIZ-AGGARWAL , @weebo-ary before making any PR weather on GitHub or Discord (On any Server).
