### ISSUE TITLE
Feat: Make UI for WE ARE SAFE !! application(idea-1)

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [awantika10/Desgen#33]
**What is your feature request related to ?**

- [x] Designing

**Description**

Maki ui design for WE ARE SAFE !! application
The design should be made using new ui technology trends 
like Glassmorphism , Neumorphism , Retro aesthetic , 3d graphics etc

`Please mention the technology you will be using to solve this issue in comments`

You can use any software you are comfortable with like Figma, AdobXD , framer etc

**Describe the solution you'd like**
```
This is an Idea for Application Named "WE ARE SAFE !!". 
This app will allow everyone of us to be safe or alert anywhere we are.
In this app we will create a account same as google account.We can add
family members to this account. If any of family member is in emergency
then with just a single click his location will be shared with his family members
and local police.This will not only help girls/women to be safe but also help 
everyone in case of medical emergency.

Features
Login/Signup Page
Option to add family members
Contacts Police and Added Family member in case of Emergency
Will help your location to get shared till police and Family only
Just single click alert
```
You can also add your features in it

**Additional context**

Please give updates of your work at least once in every 3 days ,else the issue will be assigned to others. 
Before making the final PR please ask first

**Comment by SHITIZ-AGGARWAL** [comment]
@rohank2502 since this was your idea do you want to work on this ?

**Comment by rohan-kulkarni-25** [comment]
@rohank2502  Ya it was my idea for sure but i am will not able to work on this issue as i dont have any idea for designing I just know frontend and cpp !! So it will be better if you assign this to someone who knows to design I will be happy to give him suggestion if needed so !!

**Comment by SHITIZ-AGGARWAL** [comment]
Okay no problem 👍

**Comment by ishu184** [comment]
@SHITIZ-AGGARWAL I would love to work on this. As this would be my first attempt I hope I do my best. I am familiar with figma

**Comment by SHITIZ-AGGARWAL** [comment]
Sure go ahead 👍  , if you face any problem you can refer the resources provided in the discord channel or ask from the project maintainers

**Comment by SHITIZ-AGGARWAL** [comment]
@ishu184 Please mention the technology you will be using to solve this issue

**Comment by rohan-kulkarni-25** [comment]
@ishu184  if you need any suggestion feel free to get connected !!

**Comment by ishu184** [comment]
I want to explore  Glassmorphism so will go with that! we
doubt:
1) we have to use only one technology?
2) I have to make all the features mentioned above?

**Comment by VishalPatil18** [comment]
Hey @SHITIZ-AGGARWAL, Vishal Patil here and I would love to work with @ishu184 in this issue under GSSoC'21. If possible can you assign this to me also. Also, I have experience working with Glassmorphism so I can help @ishu184 in that.
Thanks!

**Comment by awantika10** [comment]
> I want to explore Glassmorphism so will go with that! we
> doubt:
> 
> 1. we have to use only one technology?
> 2. I have to make all the features mentioned above?

You have to use glassmorphism only and all the features mentioned should be included.

**Comment by awantika10** [comment]
> Hey @SHITIZ-AGGARWAL, Vishal Patil here and I would love to work with @ishu184 in this issue under GSSoC'21. If possible can you assign this to me also. Also, I have experience working with Glassmorphism so I can help @ishu184 in that.
> Thanks!

Sure go ahead and help @ishu184

**Comment by VishalPatil18** [comment]
> > Hey @SHITIZ-AGGARWAL, Vishal Patil here and I would love to work with @ishu184 in this issue under GSSoC'21. If possible can you assign this to me also. Also, I have experience working with Glassmorphism so I can help @ishu184 in that.
> > Thanks!
> 
> Sure go ahead and help @ishu184

Will do it thanks! 

@ishu184 you can connect with me on discord "Vishal Patil(P)#3640" or Linkedin https://www.linkedin.com/in/vishalrameshpatil.
Thanks!

**Comment by arnabiscreating** [comment]
Hello @awantika10 
I have a doubt, is this a design work like I have to do it in Figma or AdobeXD or a frontend work (HTML, CSS, JS) ?
either way I want to contribute to this issue.
I am GSSOC21 participant.
Thank You.

**Comment by SHITIZ-AGGARWAL** [comment]
> Hello @awantika10
> I have a doubt, is this a design work like I have to do it in Figma or AdobeXD or a frontend work (HTML, CSS, JS) ?
> either way I want to contribute to this issue.
> I am GSSOC21 participant.
> Thank You.

You have to design it in figma or adobeXD

**Comment by SHITIZ-AGGARWAL** [comment]
But this issue have been assigned ,you can see other issues
More issues will be coming up today

**Comment by ghost** [comment]
hello @SHITIZ-AGGARWAL can i work on this issue in Adobe XD

**Comment by weebo-ary** [comment]
Hey @garvitraj , You can go ahead with this issue.

**Comment by weebo-ary** [comment]
Announcement Regarding PR -
Before Making any Pull Request Kindly Ask in The Conversation because it can conflict our master branch. 
You can ask to @awantika10 , @SHITIZ-AGGARWAL , @weebo-ary before making any PR weather on GitHub or Discord (On any Server).

**Comment by ghost** [comment]
@SHITIZ-AGGARWAL thanks for assigning it to me.
will start it today and try to deliver the best

**Comment by ishu184** [comment]
@SHITIZ-AGGARWAL I and @SpecTEviL have made the wireframing do have a look so that we can proceed further
link : https://www.figma.com/file/iOK66ticuIURVC0DEQcQW9/we-are-safe?node-id=0%3A1

**Comment by VishalPatil18** [comment]
> @SHITIZ-AGGARWAL I and @SpecTEviL have made the wireframing do have a look so that we can proceed further
> link : https://www.figma.com/file/iOK66ticuIURVC0DEQcQW9/we-are-safe?node-id=0%3A1

Also, @SHITIZ-AGGARWAL and @awantika10 if you have any suggestions for improvement do let us know, we'll work towards that. 
Thanks!

**Comment by awantika10** [comment]
@ishu184 @SpecTEviL Wireframes seems okay! The buttons seem huge and typography can be improved. Also, I am not able to see any light tone along with secondary colors ( color schemes can be improved)

**Comment by ghost** [comment]
@SHITIZ-AGGARWAL i have done with my 70% of the design work i will be giving the final output tomorrow so pls grant me one day extension

**Comment by ghost** [comment]
@SHITIZ-AGGARWAL and @awantika10 I have done with the wireframe for the app pls review it once so that I can move further with a better design applying Neumorphism. If any feedback or suggestions please guide me.
Thanks
Wireframe:- https://xd.adobe.com/view/6ba416c7-6ca0-4a82-9cd3-5137e4823fef-3ef7/

**Comment by VishalPatil18** [comment]
> @SHITIZ-AGGARWAL and @awantika10 I have done with the wireframe for the app pls review it once so that I can move further with a better design applying Neumorphism. If any feedback or suggestions please guide me.
> Thanks
> Wireframe:- https://xd.adobe.com/view/6ba416c7-6ca0-4a82-9cd3-5137e4823fef-3ef7/

Hey @garvitraj, the wireframe looks very similar to what I along with @ishu184 have made. Maybe you can try something different so that we get to see a better design or try to work on some other issue as we have started the work on this and I don't think we need more than 2 on this issue. Correct me if I'm wrong but I think @ishu184, @SHITIZ-AGGARWAL, and @awantika10 would agree with me on this.
Thanks!

**Comment by awantika10** [comment]
@garvitraj Wireframes are very similar. Try working on other issues. I guess 2 assignees are more than enough. We have a lot of issues open for your guys!

**Comment by ghost** [comment]
@awantika10 its ok mam I will definitely work on the different issue and give the better result
mam pls correct me if I m wrong in the wireframe we only just put up the functionality and feature of the app so too wireframe might look similar, I took some ideas from @SpecTEviL  design and as @SHITIZ-AGGARWAL sir mentioned the app feature already so I processed it through that. 
Thanks will definitely work on some other issue

**Comment by ishu184** [comment]
I have modified the color scheme, mentioned some fonts, and created a sample card @awantika10, @SHITIZ-AGGARWAL., @SpecTEviL 
I am not sure which font to be used so let me know your suggestion. Let me know where the improvements can be made.

**Comment by ishu184** [comment]
figma link :https://www.figma.com/file/iOK66ticuIURVC0DEQcQW9/we-are-safe?node-id=0%3A1

**Comment by awantika10** [comment]
@ishu184 @SpecTEviL  Use the lighter shade scheme for the Neumorphism design. The colour scheme and gradient which you have taken is generally used for glassmorphism. 
Also, for the font try using Sans - Serif family Roboto, etc.

**Comment by awantika10** [comment]
Wireframes looks fine

**Comment by VishalPatil18** [comment]
> @ishu184 @SpecTEviL Use the lighter shade scheme for the Neumorphism design. The colour scheme and gradient which you have taken is generally used for glassmorphism.
> Also, for the font try using Sans - Serif family Roboto, etc.

Yes, @awantika10  actually we're making this app in Glassmorphism. Hence the color scheme and gradient is chosen.
Although after discussing with @ishu184 we've decided to change the technology to Neumorphism as we both wanted to learn it and experiment and this is the best time to do so. We'll update you with the new color scheme ASAP.
So is that fine @awantika10?

**Comment by awantika10** [comment]
> > @ishu184 @SpecTEviL Use the lighter shade scheme for the Neumorphism design. The colour scheme and gradient which you have taken is generally used for glassmorphism.
> > Also, for the font try using Sans - Serif family Roboto, etc.
> 
> Yes, @awantika10 actually we're making this app in Glassmorphism. Hence the color scheme and gradient is chosen.
> Although after discussing with @ishu184 we've decided to change the technology to Neumorphism as we both wanted to learn it and experiment and this is the best time to do so. We'll update you with the new color scheme ASAP.
> So is that fine @awantika10?

No problem go ahead @ishu184 @SpecTEviL
