### ISSUE TITLE
Feat: Make UI for an application for elderly people(idea-2)

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [awantika10/Desgen#35]
**What is your feature request related to ?**

- [x] Designing

**Description**

Maki ui design for an application for elderly people
The design should be made using new ui technology trends 
like Glassmorphism , Neumorphism , Retro aesthetic , 3d graphics etc

`Please mention the technology you will be using to solve this issue in comments`

You can use any software you are comfortable with like Figma, AdobXD , framer etc

**Describe the solution you'd like**
```
Description
An application for the elderly - Everyone needs additional care and attention as they age, and elderly people are gradually becoming an increasingly large category of app users. An idea for ​​an application that will make their lives easier by planning their daily activities like reminding them about medications and utility bills, or simplifying the ordering and delivery of food products for their individual diet.

Features
This application will help in planning their daily activities like

reminding them about medications
helping them in reminding and paying their utility bills.
simplifying the ordering and delivery of food products for their individual diet.
24/7 helpline service.
daily reminders to go for a walk or exercise a little to help them stay fit.
an alert system for medical emergencies.
```
You can also add your features in it

**Additional context**

Please give updates of your work at least once in every 3 days ,else the issue will be assigned to others. 
Before making the final PR please ask first

**Comment by SHITIZ-AGGARWAL** [comment]
@sejalvasan do you want to work on this ?

**Comment by sejalvasan** [comment]
No thank you, I am not good at designing you can assign it to others.

**Comment by Ayushi7456** [comment]
Hello, May I work on this design in a group of 2 or more?

**Comment by SHITIZ-AGGARWAL** [comment]
@Ayushi7456 Sure (Max-3)

@awantika10 is this fine?

**Comment by awantika10** [comment]
> @Ayushi7456 Sure (Max-3)
> 
> @awantika10 is this fine?
Only 2 can participate at max @SHITIZ-AGGARWAL 
@Ayushi7456  You can start working

**Comment by aanya-trehan** [comment]
> Hello, May I work on this design in a group of 2 or more?

Hi @Ayushi7456, in case you haven't found a partner can we team up for this?

**Comment by Ayushi7456** [comment]
@awantika10 Ok Thankyou!
@aanya-trehan Yeah sure!

**Comment by weebo-ary** [comment]
Announcement Regarding PR -
Before Making any Pull Request Kindly Ask in The Conversation because it can conflict our master branch. 
You can ask to @awantika10 , @SHITIZ-AGGARWAL , @weebo-ary before making any PR weather on GitHub or Discord (On any Server).

**Comment by Ayushi7456** [comment]
I and @aanya-trehan making this UI design using Glassmorphism. We are beginner, learning and doing, will show our design soon.

**Comment by awantika10** [comment]
@aanya-trehan @Ayushi7456 Update?

**Comment by ShambhaviSharma0110** [comment]
hey, I'd like to work on this using neumorphism... please allow me...

**Comment by Ayushi7456** [comment]
![App for olderly ppl](https://user-images.githubusercontent.com/78416191/111364667-daa31e80-8624-11eb-9928-879a262c3cfe.JPG)
@awantika10 @SHITIZ-AGGARWAL please review our design. Do suggest if it can be improved. We will update further complete design soon.

**Comment by awantika10** [comment]
@Ayushi7456 @aanya-trehan You guys can change the gradient background. Gradient should be lighter with a combination of white-blue-green.
Size of the font can be decreased. Also, the login and signup button should be smaller. Login and SignUp text colour should be change to black as white is not visible with the green shade. 
Same goes which the other screens, you need to decrease the size of the fonts and the cards.
References :https://dribbble.com/shots/14499854-Medical-Web-App?utm_source=Clipboard_Shot&utm_campaign=ishtiaqkhanparag&utm_content=Medical%20Web%20App&utm_medium=Social_Share

**Comment by awantika10** [comment]
You can improve the illustrations too

**Comment by Ayushi7456** [comment]
Okk thankyou! we will improve it.

**Comment by awantika10** [comment]
> Okk thankyou! we will improve it.

Update?

**Comment by ambivert-sam** [comment]
Hey ! I'm participant of GSSOC'21 I want to contribute on this , can you please assign it to me ? @SHITIZ-AGGARWAL

**Comment by Ayushi7456** [comment]
@SHITIZ-AGGARWAL The issue has been closed by you, please open it once as i have to upload the remaining files as part-2 for this particular issue.

**Comment by SHITIZ-AGGARWAL** [comment]
@Ayushi7456 Update ?
