### ISSUE TITLE
Feat: Make UI for a Medicine check application(idea-3)

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [awantika10/Desgen#36]
**What is your feature request related to ?**

- [x] Designing

**Description**

Maki ui design for a Medicine check application
The design should be made using new ui technology trends 
like Glassmorphism , Neumorphism , Retro aesthetic , 3d graphics etc

`Please mention the technology you will be using to solve this issue in comments`

You can use any software you are comfortable with like Figma, AdobXD , framer etc

**Describe the solution you'd like**
```
Description
Medicine check application. A Medicine check app that focuses on remembering your medicine schedule and alerting people in special ways according to their age group.

Features
This application will help in planning their daily activities like

Login/Signup Page
kepps details of your medicine.
maintains your history.
works accordingly to age group.
also give suggestions about the best doctors near you
```
You can also add your features in it

**Additional context**

Please give updates of your work at least once in every 3 days ,else the issue will be assigned to others. 
Before making the final PR please ask first

**Comment by cryptofox17** [comment]
Could you assign this to me? I will be working on this using Figma

**Comment by SHITIZ-AGGARWAL** [comment]
@cryptofox17 Sure Go ahead
Please mention which technology you will be using like Glassmorphism , Neumorphism , Retro aesthetic , 3d graphics etc

**Comment by SHITIZ-AGGARWAL** [comment]
@Chadha93 you want to work on this issue since it was your idea ?

**Comment by cryptofox17** [comment]
@SHITIZ-AGGARWAL I was thinking of using Glassmorphism for this. 
Also, I wanted to know how to I update the progess every three days? Do I need to do it here on the comments or discord? 

Also, do this issue need to worked on as a team?

**Comment by Chadha93** [comment]
> @Chadha93 you want to work on this issue since it was your idea ?

@SHITIZ-AGGARWAL yes I have already started working on it and I'm also ready with a raw user flow which I have also shown to @awantika10 and @weebo-ary

**Comment by awantika10** [comment]
@cryptofox17 @Chadha93  You guys can collaborate and work together

**Comment by Chadha93** [comment]
ok @awantika10  you can assign me here as well @cryptofox17  please connect me on discord for further discussion regarding the project

**Comment by awantika10** [comment]
> @SHITIZ-AGGARWAL I was thinking of using Glassmorphism for this.
> Also, I wanted to know how to I update the progess every three days? Do I need to do it here on the comments or discord?
> 
> Also, do this issue need to worked on as a team?

Yes you can work in teams @cryptofox17 And update about your designs here on the issue itself

**Comment by awantika10** [comment]
> ok @awantika10 you can assign me here as well @cryptofox17 please connect me on discord for further discussion regarding the project

Also, I guess for your design two people are more than enough @cryptofox17 @Chadha93 Please collaborate on discord.

**Comment by cryptofox17** [comment]
@Chadha93 what's your username on discord? Mine is cryptofox#1638

**Comment by Chadha93** [comment]
> @Chadha93 what's your username on discord? Mine is cryptofox#1638

Gaurav Chadha(P)#7374

**Comment by arnabiscreating** [comment]
Hello @awantika10 
I'd like to contribute to this issue. I'm a member of GSSOC21. Thank you very much.

**Comment by weebo-ary** [comment]
Hey, @encodeArnab you can go ahead with this issue.

**Comment by weebo-ary** [comment]
Announcement Regarding PR -
Before Making any Pull Request Kindly Ask in The Conversation because it can conflict our master branch. 
You can ask to @awantika10 , @SHITIZ-AGGARWAL , @weebo-ary before making any PR weather on GitHub or Discord (On any Server).

**Comment by arnabiscreating** [comment]
> Hey, @encodeArnab you can go ahead with this issue.

Okay Thank You @weebo-ary

**Comment by Chadha93** [comment]
@awantika10 @SHITIZ-AGGARWAL @weebo-ary  I'm ready with my full UI for idea 3 (medicine check app) using neumorphism
can I make a PR . I am providing the screenshot of the ui, and @awantika10  in which format should I upload SVG, jpeg, fig?

![idea-3-gaurav-chadha](https://user-images.githubusercontent.com/65453826/110956401-9ab41100-8370-11eb-8ef1-b9757217e86b.jpg)

**Comment by ShambhaviSharma0110** [comment]
hey, I'd like to work on this using neumorphism...

**Comment by SHITIZ-AGGARWAL** [comment]
@ShambhaviSharma0110 you can work on other design issues this issue is assigned
