### ISSUE TITLE
Will like to add the img of tech stack it will help in making readme attractive 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [awantika10/Desgen#47]
## Expected Behavior

This will help user to grasp the used technology in short span of time !! OK so this technologies are used in this project looks quite intresting

## Steps to Reproduce the Problem

1. We can add the badges to each in place of just names

Will start work on it as soon as get assigned !!

**Comment by weebo-ary** [comment]
Do you have any example.......like a photo or link, something like that. If yes, please share it here in the conversation.

**Comment by rohan-kulkarni-25** [comment]
yes I will share example of html here 
<img alt="HTML5"  src="https://img.shields.io/badge/html5%20-%23E34F26.svg?&style=for-the-badge&logo=html5&logoColor=white"/>
Like this badges !

**Comment by madhhuurrii** [comment]
Hii @weebo-ary @rohank2502, I can add badges for our discord server as well as for the tech stack, can u please assign this issue to me ?

**Comment by awantika10** [comment]
> Hii @weebo-ary @rohank2502, I can add badges for our discord server as well as for the tech stack, can u please assign this issue to me ?

We have added that too!

**Comment by awantika10** [comment]
> yes I will share example of html here
> ![HTML5](https://camo.githubusercontent.com/5d3b0191832237fcbfc6d4497524e8bb547c6bfc9eafb738d5205c629d202067/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f68746d6c352532302d2532334533344632362e7376673f267374796c653d666f722d7468652d6261646765266c6f676f3d68746d6c35266c6f676f436f6c6f723d7768697465)
> Like this badges !

Okay you can go ahead and make a PR

**Comment by awantika10** [comment]
@rohank2502 Please add all the badges including all the technologies

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> @rohank2502 Please add all the badges including all the technologies

HTML/CSS/Figma/AdobeXD/Illustrator/Framer/Anima will add all this or there is an  addition ?
