### ISSUE TITLE
Enhancement of README.md file

### ISSUE THREAD

**Issue by anirudhsai20** [awantika10/Desgen#5]
The README.md file can be further enhanced by adding a list of all its contributors. Also the code of conduct for contributing to this project has to be mentioned.

**Comment by anirudhsai20** [comment]
Hi @awantika10 . Please allow me to work on this issue under GSSOC.

**Comment by awantika10** [comment]
Hey @anirudhsai20 You work on this issue after the coding period . Kindly join the discord channel for further discussion :)

**Comment by haripriya9647** [comment]
Hey can I work on this issue??

**Comment by awantika10** [comment]
@anirudhsai20 is working on it @haripriya9647. If he doesn't then I'll assign it to you

**Comment by SHITIZ-AGGARWAL** [comment]
@anirudhsai20 please give an update regarding this and brief about how you are going to update the readme

**Comment by anirudhsai20** [comment]
Hi @SHITIZ-AGGARWAL . I am almost done and I will be making a pull request in another half an hour. As I mentioned earlier I am going to make a beautiful and neat display of contributors.
