### ISSUE TITLE
Feat: UI for app/web "EasyJobs"

### ISSUE THREAD

**Issue by SubratYeeshu** [awantika10/Desgen#50]
**What is your feature request related to ?**

- [x] Desgen Website
- [X] Designing
- [ ] Documentation
- [ ] Others[please specify like testing, code etc]

@awantika10 / @SHITIZ-AGGARWAL Mam/Sir I would like to create UI/UX design for the app and web for Idea#11

**Comment by SHITIZ-AGGARWAL** [comment]
@SubratYeeshu I am creating issues for the same in detail , I will assign you there
