### ISSUE TITLE
Designing Nav bar

### ISSUE THREAD

**Issue by shefali12-ab** [awantika10/Desgen#53]
Hii,
I am one of participant of GSSOC'21. I would like to make the contribution by redesigning  Header, Nav Bar and footer of this website. Please, consider! And assign it to me so that I can start working on it at the earliest.
Thank you !!

**Comment by SHITIZ-AGGARWAL** [comment]
@shefali12-ab The website is not made yet. You can work on designing the website first. I will raise issue for the same, you can comment there if you want to work

**Comment by shefali12-ab** [comment]
> @shefali12-ab The website is not made yet. You can work on designing the website first. I will raise issue for the same, you can comment there if you want to work

yes , I will work on desiging the website.
