### ISSUE TITLE
Feat: Make UI for an emergency traffic clear app (idea-4)

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [awantika10/Desgen#54]
**What is your feature request related to ?**

- [x] Designing

**Description**

Maki ui design for an emergency traffic clear app
The design should be made using new ui technology trends 
like Glassmorphism , Neumorphism , Retro aesthetic , 3d graphics etc

`Please mention the technology you will be using to solve this issue in comments`

You can use any software you are comfortable with like Figma, AdobXD , framer etc

**Describe the solution you'd like**

```
Description
An app to clear traffic for emergency response vehicles- emergency vehicles such as ambulances, police cars, fire engines, etc. stuck in a traffic jam and delayed in reaching their destination can lead to loss of property and valuable lives. Whether it's a fire, medical emergency or crime, every second matters for those who need to respond to it, those precious moments are squandered. Through this application instead having drivers scramble out of the way of an emergency response vehicle when they hear sirens, this application will alert the nearby vehicles on the way beforehand.

Features
Map visualisation with colour zone(To specify the presence of any emeregency response center nearby).
On any emergency update the alert will be updated for the nearby zones of that particular center.
The alert will be pushed as a notification to the nearby vehicles using the application.
Alternate route suggestion for clearing the way.
Based on the monthly emergency cases, the application will analyse and predict for better traffic clearance of area beforehand.
Bug reporting feature.

```
You can also add your features in it

**Additional context**

Please give updates of your work at least once in every 3 days ,else the issue will be assigned to others. 
Before making the final PR please ask first

**Comment by SHITIZ-AGGARWAL** [comment]
@AkashChetia would you like to work on this since it was your idea ?

**Comment by geniusbharti** [comment]
@SHITIZ-AGGARWAL  I would like to work on this as a GSSOC'21 participant.

**Comment by SHITIZ-AGGARWAL** [comment]
@geniusbharti sure

Also please mention the technology you will be using to solve this issue in comments like Glassmorphism , Neumorphism , Retro aesthetic , 3d graphics etc

**Comment by geniusbharti** [comment]
@SHITIZ-AGGARWAL I will be using Neumorphism and Figma.

**Comment by vaibhavpathak999** [comment]
@SHITIZ-AGGARWAL I would also like to work on this same issue. I will be also be using Neumorphism using Figma. Please assign this issue to me as well. 
If you want me to try Glassmorphism I can also implement in that.

**Comment by geniusbharti** [comment]
@SHITIZ-AGGARWAL I have completed the login sign up design. I'm working on homepage now. 
![EmergencyTrafficClear](https://user-images.githubusercontent.com/75856835/111324256-9cdbdf80-8690-11eb-9013-fc1ce15af439.PNG)

**Comment by vaibhavpathak999** [comment]
> @SHITIZ-AGGARWAL I have completed the login sign up design. I'm working on homepage now.
> ![EmergencyTrafficClear](https://user-images.githubusercontent.com/75856835/111324256-9cdbdf80-8690-11eb-9013-fc1ce15af439.PNG)

Hey @geniusbharti can we discuss the home page and the feature pages. How they gonna look and what exactly we will design. If we can have a meet on discord.

**Comment by vaibhavpathak999** [comment]
![New Wireframe 1](https://user-images.githubusercontent.com/51280899/111526304-9464d100-8784-11eb-88e5-21516586560b.png)

@SHITIZ-AGGARWAL  and @awantika10  I have worked on the wireframe of this app. 
Please review it and share your views or changes (if any).

I have focused on the basics of the app. Included 6 features:
1.) Create an Emergency
2.) Find alternate pathways
3.) Search Path for the destinations.
4.) Share your current location.
5.) Bug Reporting 
6.) Contact Us

Also please tell me the time that I have for building the design. 
My wireframe does not try to give an idea for the color, theme, font, or any design. It just gives the basic elements that I will be working in design.

**Comment by awantika10** [comment]
@vaibhavpathak999 Wireframes looks good. I guess @geniusbharti and you can start with your design through these wireframes.

**Comment by vaibhavpathak999** [comment]
> @vaibhavpathak999 Wireframes looks good. I guess @geniusbharti and you can start with your design through these wireframes.

Thanks a lot @awantika10.

@geniusbharti can you dm me on discord so that we can discuss design together. my username is vaibhav#9321.

**Comment by geniusbharti** [comment]
@SHITIZ-AGGARWAL  and @awantika10  I have attached link for my designs, Could you please review and suggest me any changes needed and also color schemes.
I have made these designs using neumorphism. 
https://www.figma.com/file/AseJqXK2JeeOHaVD93KsjX/Gssoc-21-Emergency-Traffic-Clearing-App?node-id=1%3A3
