### ISSUE TITLE
Feat: Make UI for a cryptocurrency investment application (idea-5)

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [awantika10/Desgen#55]
**What is your feature request related to ?**

- [x] Designing

**Description**

Maki ui design for a cryptocurrency investment application
The design should be made using new ui technology trends 
like Glassmorphism , Neumorphism , Retro aesthetic , 3d graphics etc

`Please mention the technology you will be using to solve this issue in comments`

You can use any software you are comfortable with like Figma, AdobXD , framer etc

**Describe the solution you'd like**

```
Description
An app for investment in cryptocurrency- We find many apps in the play store for this. Some of them are Indian app also. But there some features are not available. We find these extra features in the foreign app, but they charge some amount for using those apps.

Features
Set Price Alert for any cryptocurrency.
We can set a limit for buying and selling any cryptocurrency. At first, the user sets a value for buying that cryptocurrency, when that price will come, automatically purchase will happen. This is also applicable for selling.
A user can send any cryptocurrency to other user using this app.
News section is also an important feature of this app, where users can see the news related to cryptocurrency and share it also in social media.
Bug reporting feature.

```
You can also add your features in it

**Additional context**

Please give updates of your work at least once in every 3 days ,else the issue will be assigned to others. 
Before making the final PR please ask first

**Comment by SHITIZ-AGGARWAL** [comment]
@arnab031 would you like to work on this since it was your idea

**Comment by arnab031** [comment]
I would like to contribute in it. How can I share my designing update after every 3 days?

**Comment by SHITIZ-AGGARWAL** [comment]
Great. You can share screenshots and links of the designs in the comments

**Comment by SKV-programmer** [comment]
@SHITIZ-AGGARWAL I like to work on this, kindly assign me this part..

**Comment by arnab031** [comment]
I have made some portion UI of my whole app. Here is the link - https://www.figma.com/file/nsEv5lRni5X2DLwgaMuK7a/Untitled?node-id=1%3A2 . @SHITIZ-AGGARWAL @awantika10 Please review it.

**Comment by awantika10** [comment]
@arnab031 Designs look pretty good :)) Just a small suggestions you reduce the width of the text fields given in login and register page. Do add a clay mobile mockup for better appearance of the designs.
References for clay mockups and appearance : 
https://dribbble.com/search/Neumorphism

**Comment by arnab031** [comment]
> @arnab031 Designs look pretty good :)) Just a small suggestions you reduce the width of the text fields given in login and register page. Do add a clay mobile mockup for better appearance of the designs.
> References for clay mockups and appearance :
> https://dribbble.com/search/Neumorphism

Okay. I will work on it.

**Comment by Ayushbajpai19** [comment]
Can i still work on the design??

**Comment by Bhawna147** [comment]
@SHITIZ-AGGARWAL I would like to work on this as a GSSOC'21 participant.

**Comment by awantika10** [comment]
> > @arnab031 Designs look pretty good :)) Just a small suggestions you reduce the width of the text fields given in login and register page. Do add a clay mobile mockup for better appearance of the designs.
> > References for clay mockups and appearance :
> > https://dribbble.com/search/Neumorphism
> 
> Okay. I will work on it.

Update?

**Comment by awantika10** [comment]
@SKV-programmer Are you working along with @arnab031

**Comment by awantika10** [comment]
> Can i still work on the design??

Look up for other issues please

**Comment by awantika10** [comment]
> @SHITIZ-AGGARWAL I would like to work on this as a GSSOC'21 participant.

Hey @Bhawna147 Kindly look up for other issues

**Comment by arnab031** [comment]
I have some changes in my app design. Please review it. Here is the link- https://www.figma.com/file/McWNGrm07PTJdPHjfZTPuP/Crypto-App-Design?node-id=0%3A1 @awantika10 @SHITIZ-AGGARWAL 

> > > @arnab031 Designs look pretty good :)) Just a small suggestions you reduce the width of the text fields given in login and register page. Do add a clay mobile mockup for better appearance of the designs.
> > > References for clay mockups and appearance :
> > > https://dribbble.com/search/Neumorphism
> > 
> > 
> > Okay. I will work on it.
> 
> Update?

**Comment by awantika10** [comment]
> I have some changes in my app design. Please review it. Here is the link- https://www.figma.com/file/McWNGrm07PTJdPHjfZTPuP/Crypto-App-Design?node-id=0%3A1 @awantika10 @SHITIZ-AGGARWAL
> 
> > > > @arnab031 Designs look pretty good :)) Just a small suggestions you reduce the width of the text fields given in login and register page. Do add a clay mobile mockup for better appearance of the designs.
> > > > References for clay mockups and appearance :
> > > > https://dribbble.com/search/Neumorphism
> > > 
> > > 
> > > Okay. I will work on it.
> > 
> > 
> > Update?

@arnab031 Design looks good:))) couple of changes. The white color which you have used for the cryptocurrency dashboard looks better than the rest of the screen background. Change all the screen background to white. Also, news screen can be improved. Rest looks good. After doing the above changes, you can make the PR.

**Comment by arnab031** [comment]
I have added white background in all frame. Here is the updated link - https://www.figma.com/file/McWNGrm07PTJdPHjfZTPuP/Crypto-App-Design?node-id=0%3A1 @awantika10 

> > I have some changes in my app design. Please review it. Here is the link- https://www.figma.com/file/McWNGrm07PTJdPHjfZTPuP/Crypto-App-Design?node-id=0%3A1 @awantika10 @SHITIZ-AGGARWAL
> > > > > @arnab031 Designs look pretty good :)) Just a small suggestions you reduce the width of the text fields given in login and register page. Do add a clay mobile mockup for better appearance of the designs.
> > > > > References for clay mockups and appearance :
> > > > > https://dribbble.com/search/Neumorphism
> > > > 
> > > > 
> > > > Okay. I will work on it.
> > > 
> > > 
> > > Update?
> 
> @arnab031 Design looks good:))) couple of changes. The white color which you have used for the cryptocurrency dashboard looks better than the rest of the screen background. Change all the screen background to white. Also, news screen can be improved. Rest looks good. After doing the above changes, you can make the PR.

**Comment by SKV-programmer** [comment]
> @SKV-programmer Are you working along with @arnab031

I am designing my own design

**Comment by arnab031** [comment]
> I have added white background in all frame. Here is the updated link - https://www.figma.com/file/McWNGrm07PTJdPHjfZTPuP/Crypto-App-Design?node-id=0%3A1 @awantika10
> 
> > > I have some changes in my app design. Please review it. Here is the link- https://www.figma.com/file/McWNGrm07PTJdPHjfZTPuP/Crypto-App-Design?node-id=0%3A1 @awantika10 @SHITIZ-AGGARWAL
> > > > > > @arnab031 Designs look pretty good :)) Just a small suggestions you reduce the width of the text fields given in login and register page. Do add a clay mobile mockup for better appearance of the designs.
> > > > > > References for clay mockups and appearance :
> > > > > > https://dribbble.com/search/Neumorphism
> > > > > 
> > > > > 
> > > > > Okay. I will work on it.
> > > > 
> > > > 
> > > > Update?
> > 
> > 
> > @arnab031 Design looks good:))) couple of changes. The white color which you have used for the cryptocurrency dashboard looks better than the rest of the screen background. Change all the screen background to white. Also, news screen can be improved. Rest looks good. After doing the above changes, you can make the PR.

Can I make my PR now? @awantika10
