### ISSUE TITLE
Feat: Make UI for a website that notifies about cp competitions (idea-6)

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [awantika10/Desgen#56]
**What is your feature request related to ?**

- [x] Designing

**Description**

Maki ui design for a website that notifies all the competitive programming competitions
The design should be made using new ui technology trends 
like Glassmorphism , Neumorphism , Retro aesthetic , 3d graphics etc

`Please mention the technology you will be using to solve this issue in comments`

You can use any software you are comfortable with like Figma, AdobXD , framer etc

**Describe the solution you'd like**

```
Description
A website that notifies all the competitive programming competitions going on and upcoming. We don't find an application where we get all the information about competitive coding at the same time. This will help aspirants to be updated in one place.

Add the description about the idea and add the features for the idea or how to implement the idea.

Features
Login Page
Signup page
selection of websites to be shown.
reminder to Gmail.
Blogs about how to move ahead with cp.
practice questions all diffrent cp topics.

```
You can also add your features in it

**Additional context**

Please give updates of your work at least once in every 3 days ,else the issue will be assigned to others. 
Before making the final PR please ask first

**Comment by ankitaugale23** [comment]
I would like to take this! Could you please assign it to me?  @SHITIZ-AGGARWAL

**Comment by SHITIZ-AGGARWAL** [comment]
@ASLManasa would you like to work on this since it was your idea ?

**Comment by ASLManasa** [comment]
@SHITIZ-AGGARWAL yes sir i would like to work on this.

**Comment by SHITIZ-AGGARWAL** [comment]
Great assigning you then 👍 
Also please mention the technology you will be using for the designing like  Glassmorphism , Neumorphism , Retro aesthetic , 3d graphics etc

**Comment by ASLManasa** [comment]
@SHITIZ-AGGARWAL sir i will update you by monday.

**Comment by ishu184** [comment]
@SHITIZ-AGGARWAL can I also contribute?

**Comment by ASLManasa** [comment]
@SHITIZ-AGGARWAL I would work using glassmorphism . Thank You.

**Comment by SHITIZ-AGGARWAL** [comment]
> @SHITIZ-AGGARWAL can I also contribute?

You can work with @ASLManasa on this

**Comment by ASLManasa** [comment]
@SHITIZ-AGGARWAL @awantika10 Hi , I am learning about glassmorphism. My progresss is till here. if any changes or suggestions kindly tell me. Thank you
![image](https://user-images.githubusercontent.com/72789934/111123090-ea732200-8594-11eb-844b-053f630fb393.png)

**Comment by awantika10** [comment]
> @SHITIZ-AGGARWAL @awantika10 Hi , I am learning about glassmorphism. My progresss is till here. if any changes or suggestions kindly tell me. Thank you
> ![image](https://user-images.githubusercontent.com/72789934/111123090-ea732200-8594-11eb-844b-053f630fb393.png)

@ASLManasa Please refer to the resources given in #resources channel on discord. I can't see the gradient at the background. Try changing color palette 🎨.
Refer to : https://dribbble.com/search/Glassmorphism

**Comment by ASLManasa** [comment]
@awantika10 ok mam!

**Comment by ishu184** [comment]
I have made a wireframe @awantika10 @SHITIZ-AGGARWAL let me know your suggestions and improvements that need to be made.
@ASLManasa feel free to suggest anything you would like to add
Figma link: https://www.figma.com/file/lKzeb5baOUFKXKRxifuE0m/cp?node-id=0%3A1

**Comment by Bhawna147** [comment]
can i work on this using Neumorphism ?

**Comment by SHITIZ-AGGARWAL** [comment]
@Bhawna147 you can check out other designing issues

**Comment by awantika10** [comment]
@ishu184 @ASLManasa You need not use the gradient background for the wireframes. Wireframes are usually black and white in color which are usually the rough sketches. Rest looks fine :)

**Comment by ASLManasa** [comment]
@awantika10 I have done some modifications can you check! This will be the home page. KIndly suggest if any changes can be made @ishu184
![image](https://user-images.githubusercontent.com/72789934/111589858-68c90180-87eb-11eb-9eea-051093fa7299.png)

**Comment by ASLManasa** [comment]
I have tried to complete all the pages kindly go through it and let me know if u want any changes @SHITIZ-AGGARWAL @awantika10 @ishu184  https://www.figma.com/file/Ik9IERZSo593sOS9TIFKCZ/Untitled?node-id=0%3A1

**Comment by ishu184** [comment]
https://www.figma.com/file/6THXgipQE7vgUxd2azueIT/competative-programming?node-id=326%3A2
I have given made the login pages, let me know the changes and improvements that need to be made
@SHITIZ-AGGARWAL @awantika10

**Comment by awantika10** [comment]
> https://www.figma.com/file/6THXgipQE7vgUxd2azueIT/competative-programming?node-id=326%3A2
> I have given made the login pages, let me know the changes and improvements that need to be made
> @SHITIZ-AGGARWAL @awantika10

@ishu184 @ASLManasa Kindly look up for basic design of website in dribble. You guys need to improve the color, font. Please research about it. Ping me personally if you want any help

**Comment by ASLManasa** [comment]
@awantika10  mam, updated the ideas.md file .

**Comment by ishu184** [comment]
https://www.figma.com/file/l7aJFjfTvmCmgS57nM7IC3/competative-programming-Copy?node-id=0%3A1
@awantika10 @SHITIZ-AGGARWAL please  examine and let me know the improvements and changes

**Comment by ASLManasa** [comment]
@awantika10 @SHITIZ-AGGARWAL @ishu184    we have completed our designing kindly merge it . 
link :https://www.figma.com/file/6THXgipQE7vgUxd2azueIT/competative-programming?node-id=0%3A1
Thank you

**Comment by SHITIZ-AGGARWAL** [comment]
@ASLManasa and @ishu184 you both can create a pull request , one can add the html file and the other person can add the Pngs or you both can divide the designs half-half

**Comment by ASLManasa** [comment]
@SHITIZ-AGGARWAL ok sir
