### ISSUE TITLE
Feat: Make UI for BookBuds application (idea-7)

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [awantika10/Desgen#57]
**What is your feature request related to ?**

- [x] Designing

**Description**

Maki ui design for BookBuds app : An app that provides a platform for people from all over the world to form/ join safe, virtual book clubs and connect with readers who have similar taste.

The design should be made using new ui technology trends 
like Glassmorphism , Neumorphism , Retro aesthetic , 3d graphics etc

`Please mention the technology you will be using to solve this issue in comments`

You can use any software you are comfortable with like Figma, AdobXD , framer etc

**Describe the solution you'd like**

```
Description
BookBuds - An app that provides a platform for people from all over the world to form/ join safe, virtual book clubs and connect with readers who have similar taste.

Features
Usual signup and login of a user.
Users can set up their own book club, specifying genres, location, age as parameters for finding other readers with similar tastes. Users can also join some of the already available clubs based on the same parameters.
Each book club has a common library of books that they can purchase and read, depending on what the club decides.
Each book club has an admin(usually the user who starts the club) who can reject a user's request to join their club. Other actions include conducting meetings, banning or kicking out and reporting an inappropriate user.
Users can also upload their own books (if they have a pdf/e-book version on their local storage)
While the club library is synced, each reader can read the book at their own pace by making a virtual copy of it in their own library.
Each book club has a group chat in the app which can be used to discuss their thoughts about the book, or just interact with their club members in general.
The app may additionally provide an option for the book club to have weekly/monthly/annual meetings via zoom as well.

```
You can also add your features in it

**Additional context**

Please give updates of your work at least once in every 3 days ,else the issue will be assigned to others. 
Before making the final PR please ask first

**Comment by arnabiscreating** [comment]
Greetings, @SHITIZ-AGGARWAL  I'm a GSSOC21 participant, and I'd like to take on this issue. Could you please assign it to me?
Thank You

**Comment by SHITIZ-AGGARWAL** [comment]
@encodeArnab  sure go ahead .

Also please mention the technology you will be using to solve this issue in comments like Glassmorphism , Neumorphism , Retro aesthetic , 3d graphics etc

**Comment by arnabiscreating** [comment]
Okay, I'll inform you as soon as I have any ideas.
Thank you

**Comment by P1210** [comment]
Hello, I am a GSSoC'21 Participant and i would like to work on the issue.  Can you please assign it to me?
Thank You.

**Comment by awantika10** [comment]
> Hello, I am a GSSoC'21 Participant and i would like to work on the issue. Can you please assign it to me?
> Thank You.

Sure

**Comment by awantika10** [comment]
@encodeArnab update?

**Comment by arnabiscreating** [comment]
Hello there, @awantika10 . Sorry for the delay; I will finish the designs today and will update you as soon as I do; for the designs, I am aiming for a retro aesthetic. 
Thank you so much

**Comment by arnabiscreating** [comment]
Hello there, @awantika10 . Sorry for the delay; I have completed this much, kindly review it [BookBuds](https://www.figma.com/file/E48tR8VPGlEZ9XZKYyCTJK/BookBud?node-id=0%3A1)
Thank You

**Comment by awantika10** [comment]
@SHITIZ-AGGARWAL Maybe you can suggest here.

**Comment by SHITIZ-AGGARWAL** [comment]
@encodeArnab can you come on discord voice channel , I will tell you there

**Comment by P1210** [comment]
Hello, I was assigned the issue. I have made basic user flow and outline and started working on wireframes. Will finish them soon. Let me know any changes and suggestions. Thank you.
Link to the file - https://www.figma.com/file/hdVzMMzFfXokwQiYVzIw8E/Book-Buds?node-id=2%3A1

**Comment by awantika10** [comment]
> Hello, I was assigned the issue. I have made basic user flow and outline and started working on wireframes. Will finish them soon. Let me know any changes and suggestions. Thank you.
> Link to the file - https://www.figma.com/file/hdVzMMzFfXokwQiYVzIw8E/Book-Buds?node-id=2%3A1

@P1210 User-flow looks good. You can start working

**Comment by awantika10** [comment]
@P1210 @encodeArnab You guys need to work on the same issue with the same design. Please decide and let me know

**Comment by P1210** [comment]
> @P1210 @encodeArnab You guys need to work on the same issue with the same design. Please decide and let me know

Yeah works for me.
