### ISSUE TITLE
Feat: Make UI for  Drop Application (idea-8)

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [awantika10/Desgen#58]
**What is your feature request related to ?**

- [x] Designing

**Description**

Maki ui design for drop app : It will function as an statistics application giving all information about the water resources available in ones locality.

The design should be made using new ui technology trends 
like Glassmorphism , Neumorphism , Retro aesthetic , 3d graphics etc

`Please mention the technology you will be using to solve this issue in comments`

You can use any software you are comfortable with like Figma, AdobXD , framer etc

**Describe the solution you'd like**

```
Description
The name of the app would be Drop App . It will function as an statistics application giving all information about the water resources available in ones locality.

Features
The app would tell the user regarding the water availability in ones locality and water bodies in units of gallons as well as how much days it'll last.
It'll inform them about their daily, monthly and yearly water usage as well as labelling them as Overusage, underusage or optimal usage.
Those with overusage will get a warning notification every month.
The app would also focus on water conservation and saving techniques.
It'll also give notifications regarding water shortage.
The user will also get the statistics of water being provided by the local MNC.
The user can mail grievances to the local MNC directly from the app.
The app would focus on making the usage of water optimal and stopping people from wasting it.
When the user gets the proper water statistics they'll themselves try to limit the usage and save the water.

```
You can also add your features in it

**Additional context**

Please give updates of your work at least once in every 3 days ,else the issue will be assigned to others. 
Before making the final PR please ask first

**Comment by SHITIZ-AGGARWAL** [comment]
@SpecTEviL shall I assign you ?

**Comment by Devenkapoor7303** [comment]
Can  I work on this issue?

**Comment by SHITIZ-AGGARWAL** [comment]
@Devenkapoor7303  Sure Go ahead

**Comment by VishalPatil18** [comment]
> @SpecTEviL shall I assign you ?

Yes @SHITIZ-AGGARWAL, I have made the design so I think unfortunately @Devenkapoor7303 can't contribute to this anymore because it's around 90% complete and only final finishing touches are to be done.
Sorry @Devenkapoor7303 but you can work on some other idea. 

@SHITIZ-AGGARWAL You can assign this to me along with an appropriate difficulty label so that I can make a PR once I'm 100% done. 
Thanks!

**Comment by SHITIZ-AGGARWAL** [comment]
@SpecTEviL Which technology you used ?

**Comment by VishalPatil18** [comment]
> @SpecTEviL Which technology you used ?

Adobe XD and Gimp. @SHITIZ-AGGARWAL 
I've made the wireframe as well the UI.

**Comment by SHITIZ-AGGARWAL** [comment]
@SpecTEviL I am asking about this : 
```
The design should be made using new ui technology trends
like Glassmorphism , Neumorphism , Retro aesthetic , 3d graphics etc
```

**Comment by VishalPatil18** [comment]
> I am asking about this :
> 
> ```
> The design should be made using new ui technology trends
> like Glassmorphism , Neumorphism , Retro aesthetic , 3d graphics etc
> ```

Glassmorphism

**Comment by SHITIZ-AGGARWAL** [comment]
Okay 👍

**Comment by SHITIZ-AGGARWAL** [comment]
You can share the links and ss here

**Comment by VishalPatil18** [comment]
> You can share the links and ss here

Yup, as soon as I'm done I'll do it.
Thanks!

**Comment by SHITIZ-AGGARWAL** [comment]
@Devenkapoor7303 you can work on other issues, there are many issues like this one

**Comment by Devenkapoor7303** [comment]
Okay

**Comment by VishalPatil18** [comment]
> You can share the links and ss here

1. Main Menu
![MainMenu](https://user-images.githubusercontent.com/62737267/111112386-176c0880-8586-11eb-84f8-787919f69b7e.png)

2. Notifications
![Notifications](https://user-images.githubusercontent.com/62737267/111112398-1d61e980-8586-11eb-9a0d-b806b2daa683.png)

3. Sign-in
![Signin](https://user-images.githubusercontent.com/62737267/111112409-205cda00-8586-11eb-86ee-82aba7ad7bfd.png)

4. Sign-up
![Signup](https://user-images.githubusercontent.com/62737267/111112419-25ba2480-8586-11eb-8160-0fcd15af0cf4.png)

5. Dashboard
![Dashboard](https://user-images.githubusercontent.com/62737267/111112430-2b176f00-8586-11eb-962a-42863ed4a288.png)

Hey @SHITIZ-AGGARWAL and @awantika10 I've made this design. Any suggestions are most welcomed. Do let me know if I need to make more screens or not.
Also if you think this is final then do let me know to make a mockup and then make a PR so that we get this merged.
Thanks!

**Comment by awantika10** [comment]
@SpecTEviL The buttons are huge you need reduce the size. Also, texts looks huge, please reduce the size of the text.
Refer the link :
https://dribbble.com/search/Water%20application
Check their font size, typography, etc

**Comment by VishalPatil18** [comment]
> @SpecTEviL The buttons are huge you need reduce the size. Also, texts looks huge, please reduce the size of the text.
> Refer the link :
> https://dribbble.com/search/Water%20application
> Check their font size, typography, etc

Sure will do that. Thank you for the feedback @awantika10.

**Comment by awantika10** [comment]
> > @SpecTEviL The buttons are huge you need reduce the size. Also, texts looks huge, please reduce the size of the text.
> > Refer the link :
> > https://dribbble.com/search/Water%20application
> > Check their font size, typography, etc
> 
> Sure will do that. Thank you for the feedback @awantika10.

Update @SpecTEviL

**Comment by VishalPatil18** [comment]
> > > @SpecTEviL The buttons are huge you need reduce the size. Also, texts looks huge, please reduce the size of the text.
> > > Refer the link :
> > > https://dribbble.com/search/Water%20application
> > > Check their font size, typography, etc
> > 
> > 
> > Sure will do that. Thank you for the feedback @awantika10.
> 
> Update @SpecTEviL

So sorry @awantika10, I made the changes that day itself but forgot to update you.
These are the updated frames:

![Login Screen](https://user-images.githubusercontent.com/62737267/111947866-375e7780-8b04-11eb-97ed-022b7393539a.png)
![Main Menu](https://user-images.githubusercontent.com/62737267/111947874-3c232b80-8b04-11eb-8a17-a220e6179962.png)
![My Usage](https://user-images.githubusercontent.com/62737267/111947877-3d545880-8b04-11eb-872c-544614e5bc09.png)
![Notifications](https://user-images.githubusercontent.com/62737267/111947880-3e858580-8b04-11eb-9ce2-88ba71107638.png)
![Sign Up Screen](https://user-images.githubusercontent.com/62737267/111947883-3fb6b280-8b04-11eb-93b1-e6a9e3250585.png)

**Comment by VishalPatil18** [comment]
> > > > @SpecTEviL The buttons are huge you need reduce the size. Also, texts looks huge, please reduce the size of the text.
> > > > Refer the link :
> > > > https://dribbble.com/search/Water%20application
> > > > Check their font size, typography, etc
> > > 
> > > 
> > > Sure will do that. Thank you for the feedback @awantika10.
> > 
> > 
> > Update @SpecTEviL
> 
> So sorry @awantika10, I made the changes that day itself but forgot to update you.
> These are the updated frames:
> 
> ![Login Screen](https://user-images.githubusercontent.com/62737267/111947866-375e7780-8b04-11eb-97ed-022b7393539a.png)
> ![Main Menu](https://user-images.githubusercontent.com/62737267/111947874-3c232b80-8b04-11eb-8a17-a220e6179962.png)
> ![My Usage](https://user-images.githubusercontent.com/62737267/111947877-3d545880-8b04-11eb-872c-544614e5bc09.png)
> ![Notifications](https://user-images.githubusercontent.com/62737267/111947880-3e858580-8b04-11eb-9ce2-88ba71107638.png)
> ![Sign Up Screen](https://user-images.githubusercontent.com/62737267/111947883-3fb6b280-8b04-11eb-93b1-e6a9e3250585.png)

@SHITIZ-AGGARWAL @awantika10 if you can please review once ASAP.
Thanks!
