### ISSUE TITLE
Feat: Make UI for desired product app (idea-9)

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [awantika10/Desgen#59]
**What is your feature request related to ?**

- [x] Designing

**Description**

Maki ui design for desired product app

The design should be made using new ui technology trends 
like Glassmorphism , Neumorphism , Retro aesthetic , 3d graphics etc

`Please mention the technology you will be using to solve this issue in comments`

You can use any software you are comfortable with like Figma, AdobXD , framer etc

**Describe the solution you'd like**

```
Description
How many times have you found yourself lost in the long aisles of big bazaar trying to find that one shampoo? Well, this app saves you that time! It will guide you from where you're standing to the place where you can find your desired product.

Features
Users can create a shopping list, add or remove items from it.
The app will create the shortest possible trip such that all these items can be bought.
It will also tell the user about the estimated time and cost of the shopping spree
For each product, it will display the cost and stock too.
If a product is unavailable, the app will also suggest alternatives.

```
You can also add your features in it

**Additional context**

Please give updates of your work at least once in every 3 days ,else the issue will be assigned to others. 
Before making the final PR please ask first

**Comment by SHITIZ-AGGARWAL** [comment]
@btanisha do you want to work on this since it was your idea

**Comment by btanisha** [comment]
@SHITIZ-AGGARWAL Yes, I would love to! Can I do it in Figma?

**Comment by SHITIZ-AGGARWAL** [comment]
@btanisha Sure go ahead

**Comment by SHITIZ-AGGARWAL** [comment]
Also please mention the technology you will be using to solve this issue in comments like Glassmorphism , Neumorphism , Retro aesthetic , 3d graphics etc

**Comment by yjaiswal05** [comment]
Hey, i would also like to contribute to this project . Can i do so? @SHITIZ-AGGARWAL and @btanisha

**Comment by btanisha** [comment]
@SHITIZ-AGGARWAL i've used gglassmorphism, i'll complete it by Tuesday evening.

**Comment by manognyaa** [comment]
Hey there, I think I can work on this design since am familiar with Figma and I will also use Glass morphism technology to make it more attractive. @SHITIZ-AGGARWAL 
Can I solve this issue ?

**Comment by awantika10** [comment]
> Hey, i would also like to contribute to this project . Can i do so? @SHITIZ-AGGARWAL and @btanisha

Sure @yjaiswal05

**Comment by awantika10** [comment]
@btanisha Update?

**Comment by awantika10** [comment]
> @btanisha Update?

Update?

**Comment by btanisha** [comment]
@awantika10 yash and i are working on the design. It's nearly completed.

**Comment by yjaiswal05** [comment]
Hello @SHITIZ-AGGARWAL  @awantika10  .I have completed the desired product app design with @btanisha .Please review and let me know the changes needed.
Figma:https://www.figma.com/file/3qCp54rOadvWHWcnMPTFHd/Trova?node-id=0%3A1
