### ISSUE TITLE
Microinteractions

### ISSUE THREAD

**Issue by DevrajDC** [awantika10/Desgen#6]
Microinteractions are the perfect proof that details and attention to them might greatly improve the overall user experience of your digital products and place them on the next/higher level.

**Comment by awantika10** [comment]
Hey @DevrajDC Could you please elaborate your idea for microinteractions? Also, which idea or topic you wish to design using microinteractions.

**Comment by DevrajDC** [comment]
Microinteractions as in use of Lottie animations, interactive animations etc. Which increases users experience on the site. The topic i haven't decided yet, but if anyone suggests a good topic we can integrate microinteractions to it.

**Comment by weebo-ary** [comment]
Sure we will look into this IDEA once we research on it !!
Thank you for this Idea !!!

**Comment by SHITIZ-AGGARWAL** [comment]
@DevrajDC closing this issue, will raise an issue regarding this  once the idea is confirmed , you can let us know if you want to work on documentation and designing regarding this issue
