### ISSUE TITLE
Feat: Make UI for startup solutions application (idea-10)

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [awantika10/Desgen#60]
**What is your feature request related to ?**

- [x] Designing

**Description**

Maki ui design for startup solutions application

The design should be made using new ui technology trends 
like Glassmorphism , Neumorphism , Retro aesthetic , 3d graphics etc

`Please mention the technology you will be using to solve this issue in comments`

You can use any software you are comfortable with like Figma, AdobXD , framer etc

**Describe the solution you'd like**

```
Description
An app called 'Startup Solutions' which aims to create a collaborative interface for startups

Features
login as individual/company
create your profile
pitch your startup to investors to get financing opportunities
profile/company search engine
guidance cell to assign mentors to emerging startups
Collaboration feature to work together with other startups and freelancers

```
You can also add your features in it

**Additional context**

Please give updates of your work at least once in every 3 days ,else the issue will be assigned to others. 
Before making the final PR please ask first

**Comment by vaishnavig20** [comment]
I would like to contribute to this using Figma as a GSSOC'21 participant.

**Comment by SHITIZ-AGGARWAL** [comment]
@vaishnavig20 sure go ahead .

Also please mention the technology you will be using to solve this issue in comments like Glassmorphism , Neumorphism , Retro aesthetic , 3d graphics etc

**Comment by vaishnavig20** [comment]
I would be working with neumorphism technology.

**Comment by SHITIZ-AGGARWAL** [comment]
@aanya-trehan do you want to work on this since it was your idea

**Comment by aanya-trehan** [comment]
> @aanya-trehan do you want to work on this since it was your idea

Hi! Yes, if possible, I would like to work on this. Can I work with @vaishnavig20 in this case then?

**Comment by SHITIZ-AGGARWAL** [comment]
sure

**Comment by vaishnavig20** [comment]
Hey @aanya-trehan You can connect with me on discord "Vaishnavi(P)#8611"

**Comment by vaishnavig20** [comment]
do we have to send the link to our design here or on discord?

**Comment by SHITIZ-AGGARWAL** [comment]
send here

**Comment by vaishnavig20** [comment]
https://www.figma.com/file/i1h2s9bpwHOE3zEss0KoK6/startup?node-id=0%3A1

**Comment by SHITIZ-AGGARWAL** [comment]
![image](https://user-images.githubusercontent.com/53532851/111034626-85a4b400-843c-11eb-856a-fd2d0c4df9f4.png)
It's better if you make them in same position

**Comment by SHITIZ-AGGARWAL** [comment]
![image](https://user-images.githubusercontent.com/53532851/111034656-b553bc00-843c-11eb-8171-868cf5fbbe5c.png)
Also are these suppose to be round or same as it is here

**Comment by SHITIZ-AGGARWAL** [comment]
> https://www.figma.com/file/i1h2s9bpwHOE3zEss0KoK6/startup?node-id=0%3A1

@awantika10

**Comment by vaishnavig20** [comment]
> ![image](https://user-images.githubusercontent.com/53532851/111034656-b553bc00-843c-11eb-8171-868cf5fbbe5c.png)
> Also are these suppose to be round or same as it is here

they were looking good this way

**Comment by vaishnavig20** [comment]
> > https://www.figma.com/file/i1h2s9bpwHOE3zEss0KoK6/startup?node-id=0%3A1
> 
> @awantika10

Please tell

**Comment by awantika10** [comment]
@vaishnavig20  There is a lot of chance for the improvement of the designs. You can work better. Please refer to the resources.

**Comment by manognyaa** [comment]
Hey there, I think I can work on this ui design since am familiar with Figma. I will use the Glass morphism Technolgy. @SHITIZ-AGGARWAL  Can I solve this issue?

**Comment by vaishnavig20** [comment]
> @vaishnavig20 There is a lot of chance for the improvement of the designs. You can work better. Please refer to the resources.

mam do we need to completely change it or improve few features of it. Please do tell us it would help a lot to improve the design.

**Comment by manognyaa** [comment]
Can I also contribute to the design work .
 I have experience in Figma and will use glass morphism technology .
@SHITIZ-AGGARWAL @awantika10

**Comment by awantika10** [comment]
> > @vaishnavig20 There is a lot of chance for the improvement of the designs. You can work better. Please refer to the resources.
> 
> mam do we need to completely change it or improve few features of it. Please do tell us it would help a lot to improve the design.

You need to change the whole design. Kindly refer to the resources given #resource channel in discord @vaishnavig20

**Comment by awantika10** [comment]
> Can I also contribute to the design work .
> I have experience in Figma and will use glass morphism technology .
> @SHITIZ-AGGARWAL @awantika10

We have 2 assignees, you can check out other issues

**Comment by awantika10** [comment]
@vaishnavig20  refer to https://dribbble.com/search/Neumorphism

**Comment by aanya-trehan** [comment]
> @vaishnavig20 refer to https://dribbble.com/search/Glassmorphism

Thank you! We will make changes and update you

**Comment by vaishnavig20** [comment]
> @vaishnavig20 refer to https://dribbble.com/search/Glassmorphism

mam since we were working on neumorphism technology,do u want us to use glassmorphism instead?

**Comment by awantika10** [comment]
> > @vaishnavig20 refer to https://dribbble.com/search/Glassmorphism
> 
> mam since we were working on neumorphism technology,do u want us to use glassmorphism instead?

No need :)

**Comment by aanya-trehan** [comment]
<img width="513" alt="Screenshot 2021-03-19 at 2 24 11 PM" src="https://user-images.githubusercontent.com/75018174/111755948-ad25d180-88bf-11eb-9224-52997b9cc537.png">
@SHITIZ-AGGARWAL @awantika10 Hi! We have updated our design based on your suggestions please check and let us know your feedback.

**Comment by aanya-trehan** [comment]
<img width="513" alt="Screenshot 2021-03-19 at 2 32 11 PM" src="https://user-images.githubusercontent.com/75018174/111756210-f413c700-88bf-11eb-9d19-af3d1add891c.png">
Hi! @SHITIZ-AGGARWAL @awantika10 we have updated the design based on your feedback please check and let us know what you think about it

**Comment by vaishnavig20** [comment]
> <img alt="Screenshot 2021-03-19 at 2 32 11 PM" width="513" src="https://user-images.githubusercontent.com/75018174/111756210-f413c700-88bf-11eb-9d19-af3d1add891c.png">
> 
> Hi! @SHITIZ-AGGARWAL @awantika10 we have updated the design based on your feedback please check and let us know what you think about it

Please tell so that we can improve further

**Comment by awantika10** [comment]
@vaishnavig20 @aanya-trehan You guys need to improve the text and the button size. Please take help from @Chadha93 in the discord server. Or else ping me up personally I'll assist you both

**Comment by Chadha93** [comment]
> @vaishnavig20 @aanya-trehan Sure I'm always open to help

**Comment by vaishnavig20** [comment]
> > @vaishnavig20 @aanya-trehan Sure I'm always open to help

Thank you! It would be really great if u could check the link
 https://www.figma.com/file/i1h2s9bpwHOE3zEss0KoK6/startup?node-id=0%3A1
The  above link has the design we are working on

**Comment by Chadha93** [comment]
The template looks great!
what you can do is:-
1. remove the outer stroke(or border) from every template
2. make text and buttons a little small 
3. even the typography 
4. reduce the size of icons and can refer to some more SVG from icons8.com

**Comment by aanya-trehan** [comment]
> The template looks great!
> what you can do is:-
> 
> 1. remove the outer stroke(or border) from every template
> 2. make text and buttons a little small
> 3. even the typography
> 4. reduce the size of icons and can refer to some more SVG from icons8.com

Thank you for the feedback! We will work on this and get back to you

**Comment by vaishnavig20** [comment]
https://www.figma.com/file/i1h2s9bpwHOE3zEss0KoK6/startup?node-id=0%3A1
Please look into the design as we have made the few changes suggested and have also done prototyping for the same.
@awantika10 @SHITIZ-AGGARWAL

**Comment by vaishnavig20** [comment]
> https://www.figma.com/file/i1h2s9bpwHOE3zEss0KoK6/startup?node-id=0%3A1
> Please look into the design as we have made the few changes suggested and have also done prototyping for the same.
> @awantika10 @SHITIZ-AGGARWAL

Please look into this and let us know
