### ISSUE TITLE
Feat: Make UI for easyjobs application (idea-11)

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [awantika10/Desgen#61]
**What is your feature request related to ?**

- [x] Designing

**Description**

Maki ui design for EasyJobs application
The design should be made using new ui technology trends 
like Glassmorphism , Neumorphism , Retro aesthetic , 3d graphics etc

`Please mention the technology you will be using to solve this issue in comments`

You can use any software you are comfortable with like Figma, AdobeXD , framer etc

**Describe the solution you'd like**

```
Description .
This is an Idea for Application Named "EasyJobs". If anyone wants a homemaker or construction worker for home or small cap projects or any other kind of work. This app will generate a specific ad with requirements needed and if an employee wants to work here can ping the employer through the app. Also this app can be used to keep track on their employees. This will ease finding a suitable worker for home in a fast and efficient way. This app will also ensure safety of the user and timely payment of the employee.

Features
Login/Signup Page - For employee and employer
Verification of employee through the app
Prompt for Location access to both employee and employer
Employee management and monitoring dashboard
Rating and feedback for work
Customer support tab

```
You can also add your features in it

**Additional context**

Please give updates of your work at least once in every 3 days ,else the issue will be assigned to others. 
Before making the final PR please ask first

**Comment by SHITIZ-AGGARWAL** [comment]
@SubratYeeshu Do you want to work on this ?

**Comment by SubratYeeshu** [comment]
Yes @SHITIZ-AGGARWAL sir
Can you please assign it to me

**Comment by SHITIZ-AGGARWAL** [comment]
@SubratYeeshu sure 

Also please mention the technology you will be using to solve this issue in comments like Glassmorphism , Neumorphism , Retro aesthetic , 3d graphics etc

**Comment by awantika10** [comment]
@SubratYeeshu Update?

**Comment by SubratYeeshu** [comment]
Yes @awantika10 mam, working on it need one more day

**Comment by lavishabhambri** [comment]
Hey @SHITIZ-AGGARWAL and @awantika10 I want to work on this issue. I will be using Neumorphism in Figma. Please assign this issue to me.

**Comment by SubratYeeshu** [comment]
@SHITIZ-AGGARWAL sir how can i create a pull request for my design on figma

**Comment by SHITIZ-AGGARWAL** [comment]
@SubratYeeshu Please share the designs here first then you can create a pull request

**Comment by SubratYeeshu** [comment]
![EasyJobs](https://user-images.githubusercontent.com/75444646/111571653-1bd63280-87cd-11eb-89ff-2d79f5fbd032.png) @SHITIZ-AGGARWAL  sir

**Comment by SubratYeeshu** [comment]
@SHITIZ-AGGARWAL sir, https://www.figma.com/file/dauLg1PUdlxoXtZes0Nxe6/EasyJobs

**Comment by awantika10** [comment]
@SubratYeeshu Which technology have you used for the design?

**Comment by SubratYeeshu** [comment]
neomorphism @awantika10  mam

**Comment by lavishabhambri** [comment]
@awantika10 and @SHITIZ-AGGARWAL sir, I have made the wireframe for EasyJobs Application. Kindly review it and share your suggestions & changes (if any).
![New Wireframe 1](https://user-images.githubusercontent.com/56781728/111777481-5cbb6d80-88d9-11eb-8922-ca73ccc64e68.png)

**Comment by awantika10** [comment]
> @awantika10 and @SHITIZ-AGGARWAL sir, I have made the wireframe for EasyJobs Application. Kindly review it and share your suggestions & changes (if any).
> ![New Wireframe 1](https://user-images.githubusercontent.com/56781728/111777481-5cbb6d80-88d9-11eb-8922-ca73ccc64e68.png)

Looks good :) @lavishabhambri @SubratYeeshu You both can start working on this.
