### ISSUE TITLE
A logo for desgen

### ISSUE THREAD

**Issue by fomalhauting** [awantika10/Desgen#69]
I would like to design a logo for desgen. 
Kindly assign it to me, under gssoc

- [x] Desgen Website
- [x] Designing
- [ ] Documentation
- [ ] Others[please specify like testing, code etc]

**Description**
What is your feature request ? (A description of the feature. Write about the problem or idea you want to refer in this issue.)

**Describe the solution you'd like**
A description of the solution you would suggest if any. (Any suggestions for issue solving)

**Additional context**

**Comment by awantika10** [comment]
@itsIapetus We are currently not looking for change in logo. You can work on other issues. I am closing the issue right now,may open this in future.
