### ISSUE TITLE
Feat: Make 3D Illustrations and Animations 

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [awantika10/Desgen#74]
**What is your feature request related to ?**

- [x] Designing
- [x] Others : Making 3d illustrations and animations

**Description**

Make 3d illustrations or animations ( the illustrations can be related to any topic but they should be 3d and not copied from anywhere). You have to add in  .png or .jpg format. In the designs folder make a new folder (name should be related to illustrations) , in that folder you have to add the illustrations and a html file  ([template of html file](https://github.com/awantika10/Desgen/blob/gssoc/Designs/DesignTemplate_IdeaName.html))

Please ask before making a pr ( you have to show the designs in the comment section first : you can also share the link )

**{ MINIMUM 7 ILLUSTRATIONS }** 
or
**{ MINIMUM 3 ANIMATION }**

**Comment by vaibhavpathak999** [comment]
Hey, @SHITIZ-AGGARWAL I want to work on this issue. I find it cool and amazing. I have worked on three 3D games in Unity. I would love to contribute to this issue. It would be great if you can give me examples of 3D illustrations and animations. And can you explain about the theme on which I have to make them?

**Comment by awantika10** [comment]
> Hey, @SHITIZ-AGGARWAL I want to work on this issue. I find it cool and amazing. I have worked on three 3D games in Unity. I would love to contribute to this issue. It would be great if you can give me examples of 3D illustrations and animations. And can you explain about the theme on which I have to make them?

@vaibhavpathak999 You can make the 3D illustrations and animations using blender,maya,unity.
Sample is given below and you can make on any theme.
![images](https://user-images.githubusercontent.com/71998138/111262370-303df200-864a-11eb-910b-8ceef498fb34.jpeg)

**Comment by jhasuraj01** [comment]
@SHITIZ-AGGARWAL I have worked on one UI animation, can I make a PR for it?


https://user-images.githubusercontent.com/44930179/111616576-0df1d300-8808-11eb-8391-b79f3b0e988b.mp4

**Comment by awantika10** [comment]
> @SHITIZ-AGGARWAL I have worked on one UI animation, can I make a PR for it?
> 
>  Media1.mp4

@SHITIZ-AGGARWAL Can we include this?

**Comment by awantika10** [comment]
> @SHITIZ-AGGARWAL I have worked on one UI animation, can I make a PR for it?
> 
>  Media1.mp4

@jhasuraj01 by 3D animation we mean to say, Animations made using blender, unity, echoAR etc.

**Comment by jhasuraj01** [comment]
> > @SHITIZ-AGGARWAL I have worked on one UI animation, can I make a PR for it?
> > 
> >  Media1.mp4
> 
> @jhasuraj01 by 3D animation we mean to say, Animations made using blender, unity, echoAR etc.

Okay 👍

**Comment by kunal299** [comment]
@awantika10 @SHITIZ-AGGARWAL I have  made a corona virus model in blender. Will it be included?

![image](https://user-images.githubusercontent.com/71486434/112433245-fb2b5100-8d67-11eb-8079-588aa73647d5.png)

**Comment by kunal299** [comment]
@awantika10 @SHITIZ-AGGARWAL Can I make a pr?

**Comment by SHITIZ-AGGARWAL** [comment]
@kunal299 since it is a level 3 issue , we expect a certain number of illustrations to be submitted. You can try other illus like 3d masks , gloves, lab coats etc related to corona virus along with this illustration. Also please add colours to this 😊.

**Comment by subhasmitapradhan** [comment]
can I still contribute in this?

**Comment by SHITIZ-AGGARWAL** [comment]
@subhasmitapradhan  yes

**Comment by subhasmitapradhan** [comment]
Here is something I created using blender with concept of SAVING THE PLANTS AND TREES. Can I make a PR for it ?

![image](https://user-images.githubusercontent.com/78353431/113380513-4a0d5380-9331-11eb-8481-91b59d11bec5.png)

**Comment by subhasmitapradhan** [comment]
Here is something I worked on with the concept "SAVE THE TREES AND PLANTS". 
![2](https://user-images.githubusercontent.com/78353431/113387585-703aef80-9341-11eb-8827-f2afd3c60e26.png)

**Comment by subhasmitapradhan** [comment]
please let me know ,if it needs some changes or can I make a PR?

**Comment by SHITIZ-AGGARWAL** [comment]
@subhasmitapradhan please make more illustrations as mentioned in the description. You can either change the colour or remove the background in this one

**Comment by subhasmitapradhan** [comment]
Ok..so as per the description I have to make minimum 7 illustations. So do i have to add more elements to the above illustation or make 6 more illustationa like the above one?
And does all the illustrations need to be on same topic?

**Comment by Bhawna147** [comment]
@SHITIZ-AGGARWAL @awantika10  I have make some 3D illustrations please let me know if these type of illustrations are accepted or not if yes  can I work on more such designs ??

![Screenshot_20210412-164900_Prisma3D.jpg](https://user-images.githubusercontent.com/79100530/114387761-72f2db80-9bb0-11eb-8381-005c062faf28.jpg)![Screenshot_20210412-165104_Prisma3D.jpg](https://user-images.githubusercontent.com/79100530/114387768-76866280-9bb0-11eb-8e96-35692a169dd2.jpg)![Screenshot_20210412-165433_Prisma3D.jpg](https://user-images.githubusercontent.com/79100530/114387775-78e8bc80-9bb0-11eb-8575-61e3f50585f3.jpg)![Screenshot_20210412-165442_Prisma3D.jpg](https://user-images.githubusercontent.com/79100530/114387781-7be3ad00-9bb0-11eb-8f71-b3d08fe5f137.jpg)

**Comment by vermatanu** [comment]
is this issue still open?
