### ISSUE TITLE
Greeting Bot

### ISSUE THREAD

**Issue by muthuannamalai12** [awantika10/Desgen#76]
Create a Contributor Greetings Bot.
Every Contributor to an OpenSource Project is special that is why I feel We should add a small GithubAction to give a warm welcome to the contributors.

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of Girl Script Summer Of Code. Kindly assign it to me.

**Comment by awantika10** [comment]
@muthuannamalai12 We are currently not looking for this feature. May open this issue in future
