### ISSUE TITLE
Medical App's: Web Version

### ISSUE THREAD

**Issue by vaibhavpathak999** [awantika10/Desgen#78]
**What is your feature request related to ?**

- [x] Desgen Website
- [X] Designing
- [ ] Documentation
- [ ] Others[please specify like testing, code etc]

A medical web application that will be built using react. An almost similar idea is present in idea.md for mobile-based applications.
What is your feature request? (A description of the feature. Write about the problem or idea you want to refer in this issue.)
For now, features can be the same as present in medical app ideas.

A description of the solution you would suggest if any. (Any suggestions for issue solving)
A whole mass of people uses web-based applications for different purposes. And with Responsive design and React framework we are able to use websites as mobile apps. 
Many pharmaceuticals and health-based companies nowadays have their web application as well. For example https://www.practo.com/

**Comment by awantika10** [comment]
@vaibhavpathak999 Closing the issue. We have similar issues for these, kindly look for the same

**Comment by vaibhavpathak999** [comment]
> @vaibhavpathak999 Closing the issue. We have similar issues for these, kindly look for the same

Ok @awantika10
