### ISSUE TITLE
Feat: Add new Ideas for Desgen

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [awantika10/Desgen#8]
**Description**
 
We want innovative ideas for Desgen
( Innovative ideas which solve our day to day problems or major problems of society. 
We will try to solve these problem with designing )

eg: Designing a application that makes it safe to find an ideal roommate in a new city

**FIRST COMMENT ON THE ISSUE BEFORE MAKING A PR ASKING IF YOU CAN MAKE A PR FOR THIS IDEA, WE WILL TELL YOU IF YOU CAN MAKE A PR OR NOT**

`Add the idea in the ideas.md
You have to add a proper description about the idea and features for the idea(like how we can implement the idea)
If you have any design/mockup/workflow for the idea you can also add them
`
`The ideas should be unique or innovative`

**Additional context**

Follow the template

```
## Idea number

### Name

### Description 

### Features
 - (Minimum 4 features)
 -
### Design(if made)

```

This is an open issue . You can directly make a pr , no need of getting assigned(provided that the idea is innovative/unique and have a good explanation)

**Comment by deek121477** [comment]
Hey, I would love to contribute to this issue . Could you plz assign me?

**Comment by rohank2502** [comment]
Will like to work under your guidance !!

**Comment by chiragagrawal9200** [comment]
I would love to contribute to this project . Please could you take me in?

**Comment by SHITIZ-AGGARWAL** [comment]
@deek121477 and @chiragagrawal9200 you can start working on this  and make a Pr .This is an open issue , no need of assigning

**Comment by FireQueen-3010** [comment]
Hi, I would like to work on this as well!

**Comment by weebo-ary** [comment]
Ask in the conversation before making any PR.

**Comment by Yaji16** [comment]
I wish to work on this issue.

**Comment by arnab031** [comment]
Can I share my new ideas about cryptocurrency trading app? @SHITIZ-AGGARWAL @awantika10

**Comment by SHITIZ-AGGARWAL** [comment]
@Yaji16 @AkashChetia  please first ask about raising the pr in comments then make a pr when the mentors or project admin allow else merge conflicts will arise

**Comment by AkashChetia** [comment]
> @Yaji16 @AkashChetia please first ask about raising the pr in comments then make a pr when the mentors or project admin allow else merge conflicts will arise

@SHITIZ-AGGARWAL My bad! will make sure from next time.

**Comment by arnab031** [comment]
Sir, can I make pr? https://github.com/awantika10/Desgen/issues/8#issuecomment-795484253
@SHITIZ-AGGARWAL

**Comment by SHITIZ-AGGARWAL** [comment]
> Can I share my new ideas about cryptocurrency trading app? @SHITIZ-AGGARWAL @awantika10

@arnab031 
sure go ahead
**Add it as idea 5**

**Comment by ASLManasa** [comment]
Sir,can I make a Pr  #8(comment)
@SHITIZ-AGGARWAL

**Comment by awantika10** [comment]
> Sir,can I make a Pr #8(comment)
> @SHITIZ-AGGARWAL

Sure go ahead Add it as idea 6. Make sure your fork is updated after idea 5

**Comment by aashishah** [comment]
Hi, I'd like to contribute an app idea, can I make a PR?

**Comment by SHITIZ-AGGARWAL** [comment]
@ASLManasa You can make the pr now

**Comment by SHITIZ-AGGARWAL** [comment]
> Hi, I'd like to contribute an app idea, can I make a PR?

@aashishah Sure, Add it as idea-7
You can make the pr after idea 6 is merged

**Comment by ASLManasa** [comment]
Sir, i have made a pr (idea-6)
@SHITIZ-AGGARWAL

**Comment by VishalPatil18** [comment]
Hey @SHITIZ-AGGARWAL I'm Vishal Patil, a participant at GSSoC'21. I have an Idea can I make a PR? If yes please assign an idea number to me.
Thanks!

**Comment by jyotsana3108** [comment]
Hey, I would love to contribute to this issue . I am participant of GSSOC-21. Could you please assign it to me?

**Comment by awantika10** [comment]
> Hey @SHITIZ-AGGARWAL I'm Vishal Patil, a participant at GSSoC'21. I have an Idea can I make a PR? If yes please assign an idea number to me.
> Thanks!

Sure go ahead with idea -8 and update your fork after idea -7

**Comment by aanya-trehan** [comment]
Hi! I am a participant of GSSoC'21, and I want to share my app idea! Can I please be assigned an idea number whenever possible? Thank you

**Comment by awantika10** [comment]
> Hey, I would love to contribute to this issue . I am participant of GSSOC-21. Could you please assign it to me?

Add it as idea -9 please make a PR after idea -8 and update your fork

**Comment by awantika10** [comment]
> Hi! I am a participant of GSSoC'21, and I want to share my app idea! Can I please be assigned an idea number whenever possible? Thank you

Add it as idea -10 . Please update your fork after idea -9 and make your PR

**Comment by SHITIZ-AGGARWAL** [comment]
@aashishah you can make the PR now as idea 7, Ides 6 is merged(remember to update your repo)

**Comment by aashishah** [comment]
> @aashishah you can make the PR now as idea 7, Ides 6 is merged(remember to update your repo)

Yeah, just working on it please give me some time.

**Comment by SHITIZ-AGGARWAL** [comment]
> > @aashishah you can make the PR now as idea 7, Ides 6 is merged(remember to update your repo)
> 
> Yeah, just working on it please give me some time.

no problem 👍  take your time , just keep your  idea as much detailed as possible and add good features in it

**Comment by Yaji16** [comment]
Hey @SHITIZ-AGGARWAL , I would like to work on this issue. Please can you assign it to me?

**Comment by aashishah** [comment]
> > > @aashishah you can make the PR now as idea 7, Ides 6 is merged(remember to update your repo)
> > 
> > 
> > Yeah, just working on it please give me some time.
> 
> no problem 👍 take your time , just keep your idea as much detailed as possible and add good features in it

Hey, I've made the PR.

**Comment by ShreyaJindal** [comment]
I would like to make a PR, please assign me a number.

**Comment by SHITIZ-AGGARWAL** [comment]
> Hey @SHITIZ-AGGARWAL , I would like to work on this issue. Please can you assign it to me?

@Yaji16 sure
Add it as idea 11 . Please make a pr after idea 10 gets merged, and update your repo before making pr

**Comment by SHITIZ-AGGARWAL** [comment]
> I would like to make a PR, please assign me a number.

@ShreyaJindal sure
Add it as idea 12 . Please make a pr after idea 11 gets merged, and update your repo before making pr

**Comment by SHITIZ-AGGARWAL** [comment]
@SpecTEviL you can make the PR now as idea 8, Ides 7 is merged(remember to update your repo)

**Comment by VishalPatil18** [comment]
> @SpecTEviL you can make the PR now as idea 8, Ides 7 is merged(remember to update your repo)

I've made the PR @SHITIZ-AGGARWAL. You can review it.
Thanks!

**Comment by FireQueen-3010** [comment]
Hi, @SHITIZ-AGGARWAL , I am ready with an idea description, under what idea number can I make a pull request now?

**Comment by awantika10** [comment]
@FireQueen-3010 Please wait for some time. Till rest of the PRs and the ideas get merged

**Comment by FireQueen-3010** [comment]
Yeah sure, Thank you.  Can I take idea 13, because the assigned are till 12 so that I can make a pr after 12 is merged? @awantika10 
@SHITIZ-AGGARWAL

**Comment by Rayman-Sodhi** [comment]
Hi @SHITIZ-AGGARWAL   and @awantika10  I too have an idea. It would be really helpful if you can let me know when can I be assigned an idea number. I have the description in mind please let me know when can I raise a PR

**Comment by weebo-ary** [comment]
Hey @Rayman-Sodhi, Be ready with your idea we will let you know the number when the pending idea request will be merged. Kindly wait for sometime.

**Comment by weebo-ary** [comment]
Announcement Regarding PR -
Before Making any Pull Request Kindly Ask in The Conversation because it can conflict our master branch. 
You can ask to @awantika10 , @SHITIZ-AGGARWAL , @weebo-ary before making any PR weather on GitHub or Discord (On any Server).

**Comment by vaishnavig20** [comment]
Hey @awantika10.I would also like to contribute an idea.I am a GSSOC'21 participant

**Comment by ankitaugale23** [comment]
Hello, can I work on their ideas added in the ideas.md, or the people who have added it can only work on them? Please let me know. @awantika10 @SHITIZ-AGGARWAL  
Thank you

**Comment by madhhuurrii** [comment]
Hey @SHITIZ-AGGARWAL @awantika10, I have an idea that I would like to work in, can I make a PR, and under which number?

**Comment by awantika10** [comment]
> Yeah sure, Thank you. Can I take idea 13, because the assigned are till 12 so that I can make a pr after 12 is merged? @awantika10
> @SHITIZ-AGGARWAL

Sure go ahead with idea-13

**Comment by awantika10** [comment]
> Hi @SHITIZ-AGGARWAL and @awantika10 I too have an idea. It would be really helpful if you can let me know when can I be assigned an idea number. I have the description in mind please let me know when can I raise a PR

@Rayman-Sodhi You can take idea-14

**Comment by awantika10** [comment]
> Hey @awantika10.I would also like to contribute an idea.I am a GSSOC'21 participant

Take idea -15

**Comment by awantika10** [comment]
> Hello, can I work on their ideas added in the ideas.md, or the people who have added it can only work on them? Please let me know. @awantika10 @SHITIZ-AGGARWAL
> Thank you

You can take idea-16

**Comment by awantika10** [comment]
> Hey @SHITIZ-AGGARWAL @awantika10, I have an idea that I would like to work in, can I make a PR, and under which number?

You can idea -17

**Comment by jyotsana3108** [comment]
> Hey, I would love to contribute to this issue . I am participant of GSSOC-21. Could you please assign it to me?

Heyy @awantika10 actually I am unable to get if you had replied for my comment or not. If you had replied for it then please again reply by mentioning me with the idea number. If not then its fine I will wait.

**Comment by Shweta200126** [comment]
Hi @awantika10 and @SHITIZ-AGGARWAL, I have an idea too. Please assign me an idea number.

**Comment by FireQueen-3010** [comment]
@awantika10  @SHITIZ-AGGARWAL @weebo-ary , ready to merge idea 13 (which u assigned) , shall I make a pull request now?

**Comment by Anushka-Rajvanshi** [comment]
Hi @awantika10 and @SHITIZ-AGGARWAL , I also want to add an idea. Please assign me an idea number.

**Comment by SHITIZ-AGGARWAL** [comment]
> @awantika10 @SHITIZ-AGGARWAL @weebo-ary , ready to merge idea 13 (which u assigned) , shall I make a pull request now?

go ahead

**Comment by SHITIZ-AGGARWAL** [comment]
> > Hey, I would love to contribute to this issue . I am participant of GSSOC-21. Could you please assign it to me?
> 
> Heyy @awantika10 actually I am unable to get if you had replied for my comment or not. If you had replied for it then please again reply by mentioning me with the idea number. If not then its fine I will wait.

@jyotsana3108  You can take **Idea -18** now. Let idea 17 get merged then you can create a pr (update your fork before making pr)(

**Comment by SHITIZ-AGGARWAL** [comment]
> Hi @awantika10 and @SHITIZ-AGGARWAL, I have an idea too. Please assign me an idea number.

@Shweta200126  You can take **Idea -19** . Let idea 18 get merged then you can create a pr (update your fork before making pr)

**Comment by SHITIZ-AGGARWAL** [comment]
> Hi @awantika10 and @SHITIZ-AGGARWAL , I also want to add an idea. Please assign me an idea number.

@Anushka-Rajvanshi  You can take **Idea -20** . Let idea 19 get merged then you can create a pr (update your fork before making pr)

**Comment by FireQueen-3010** [comment]
I've made a pull request for idea 13 please accept.

**Comment by Rayman-Sodhi** [comment]
I've made a  pull request for idea 14. Kindly check it.

**Comment by guruc-134** [comment]
Hi , I would like to work on it please assign me a number .

**Comment by Yaji16** [comment]
Hey @awantika10 , could you please assign me an idea number?

**Comment by mondalraj** [comment]
@SHITIZ-AGGARWAL I want to add an idea, please assign me a number for the same

**Comment by ambivert-sam** [comment]
Hey, I would love to contribute to this issue . I want to add an idea  please assign me a number for the same
Could you plz assign me?

**Comment by yjaiswal05** [comment]
Hey @SHITIZ-AGGARWAL @awantika10 , I have an idea that I would like to work on, can I make a PR, and under which number?

**Comment by SHITIZ-AGGARWAL** [comment]
**IMPORTANT
We are closing this issue for now , first the designs for existing ideas will be made then this issue will be opened again. Issues till 20 are assigned (16, 17, 18, 19, 20 are left to be merged). Please start making  pr number wise asap**

@ankitaugale23 (idea 16)
@madhhuurrii (idea 17)
@jyotsana3108 (idea 18)
@Shweta200126 (idea 19)
@Anushka-Rajvanshi (idea-20)

All the tagged contributors should make pr when the earlier number is merged
Rest of the people can work on other available issues

**Comment by madhhuurrii** [comment]
Hii @ankitaugale23 are u making a PR for idea-16?

**Comment by madhhuurrii** [comment]
Hi @SHITIZ-AGGARWAL @awantika10 ,as currently idea 16 PR has not been made , should I proceed by making a PR else wait?

**Comment by SHITIZ-AGGARWAL** [comment]
@madhhuurrii go ahead , make a pr as idea 16

**Comment by SHITIZ-AGGARWAL** [comment]
@jyotsana3108 add your idea as idea 16
please do it as soon as possible

**Comment by jyotsana3108** [comment]
I had made a PR please verify and merge it @awantika10 and @SHITIZ-AGGARWAL

**Comment by Shweta200126** [comment]
@jyotsana3108 I can't see ur idea in the main PRs here. Pls, try to do that again.

**Comment by jyotsana3108** [comment]
I had again made a PR please verify and merge it @awantika10 and @SHITIZ-AGGARWAL and @Shweta200126

**Comment by ShambhaviSharma0110** [comment]
Hey this project is really intriguing and since I'm a beginner could you please allow me to make a pr?

**Comment by kshitija-2001** [comment]
Hey, I would love to contribute to this issue. Please can you allow me to make a pr?

**Comment by awantika10** [comment]
@ShambhaviSharma0110 @kshitija-2001 We won't be working further on this issue. You can check other issues and start contributing for it :)

**Comment by Anushka-Rajvanshi** [comment]
Can I also not make a PR? I was already assigned a number and was waiting for my turn. @awantika10 @SHITIZ-AGGARWAL

**Comment by SHITIZ-AGGARWAL** [comment]
> Can I also not make a PR? I was already assigned a number and was waiting for my turn. @awantika10 @SHITIZ-AGGARWAL

@Anushka-Rajvanshi make your PR , as idea 18
as soon as possible
