### ISSUE TITLE
Create A Brand New Website For Our Designs !!

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [awantika10/Desgen#82]
**What is your feature request related to ?**

- [x] Desgen Website
- [ ] Designing
- [ ] Documentation
- [ ] Others[please specify like testing, code etc]

**Description**
What is your feature request ? (A description of the feature. Write about the problem or idea you want to refer in this issue.)

I will like to create a website for our own ideas than add the ideas to other platform why not to create a website of our own !! I know how to host It on github as github pages !! Backend might be an big issue for this But IF someone is ready for doing backend work This will the great !!

**Describe the solution you'd like**
A description of the solution you would suggest if any. (Any suggestions for issue solving)

**Additional context**

**Comment by SHITIZ-AGGARWAL** [comment]
@rohank2502 first the designs will be made for the website , then this will start

**Comment by SHITIZ-AGGARWAL** [comment]
I am raising the issue for designing the website , if interested you can comment on it. If you only want to work on coding part then you will have to wait till designs are finalised

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> I am raising the issue for designing the website , if interested you can comment on it. If you only want to work on coding part then you will have to wait till designs are finalised

Ok will wait :)
