### ISSUE TITLE
Feat: Make UI for a tutor finding application (idea-12)

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [awantika10/Desgen#84]
**What is your feature request related to ?**

- [x] Designing

**Description**

Maki ui design for an application through which students and parents can hire a tutor.
The design should be made using new ui technology trends 
like Glassmorphism , Neumorphism , Retro aesthetic , 3d graphics etc

`Please mention the technology you will be using to solve this issue in comments`

You can use any software you are comfortable with like Figma, AdobeXD , framer etc

**Describe the solution you'd like**

```
Description
Design an application through which students and parents can hire a tutor.

Features
Find a tutor according to your requirements like fees, subjects, etc.
Have in-app doubt support.
Demo video from each teacher and chat facility with them.
Rating and reviews for each teacher.
Child's progress updated by the tutor.
Weekly challenges

```
You can also add your features in it

**Additional context**

Please give updates of your work at least once in every 3 days ,else the issue will be assigned to others. 
Before making the final PR please ask first

**Comment by deeptea22** [comment]
Hey! I would like to work on this issue using neumorphism on figma. Please assign this to me as a part of GSSoC'21. Thanks :)

**Comment by ghost** [comment]
hey i would like to work on the issue in XD pls assign this issue to me as a part of Gssoc21

**Comment by manognyaa** [comment]
hey can I work on this I will use neumorphism technology via figma ? @SHITIZ-AGGARWAL

**Comment by SHITIZ-AGGARWAL** [comment]
Assigning @deeptea22 and @garvitraj 

@manognyaa you can check out #85 . If you want to work on it I will assign it to you

**Comment by SHITIZ-AGGARWAL** [comment]
@garvitraj Mention how you are going to solve this like using Glassmorphism , Neumorphism , Retro aesthetic , 3d graphics etc

**Comment by manognyaa** [comment]
@SHITIZ-AGGARWAL Yes sir, definitely I will do.
 pls assign me the work .

**Comment by SHITIZ-AGGARWAL** [comment]
> @SHITIZ-AGGARWAL Yes sir, definitely I will do.
> pls assign me the work .

done 👍

**Comment by ShreyaJindal** [comment]
@SHITIZ-AGGARWAL, Can I work on this issue?

**Comment by ghost** [comment]
@SHITIZ-AGGARWAL i was planning to do it with Neumorphism and try to include some 3d component
i and @deeptea22 together work on it on Figma only as i too familiar with Figma if u permit?

**Comment by deeptea22** [comment]
https://www.figma.com/file/XsiAbwGmeozKOJQ6my4G4X/Tutoring-App?node-id=0%3A1
This is what i've done so far. Please let me know if there are any changes. Thank you :)
@SHITIZ-AGGARWAL

**Comment by ghost** [comment]
@SHITIZ-AGGARWAL and @awantika10 any suggestions on this design till now so or any improvement then please tell.
i will be completing it by today
![Capture](https://user-images.githubusercontent.com/62978449/111813342-1547d800-88ff-11eb-88f2-0a1b89854a29.PNG)

**Comment by awantika10** [comment]
@garvitraj @deeptea22 You guys need to work on same designs.

**Comment by awantika10** [comment]
> @SHITIZ-AGGARWAL and @awantika10 any suggestions on this design till now so or any improvement then please tell.
> i will be completing it by today
> ![Capture](https://user-images.githubusercontent.com/62978449/111813342-1547d800-88ff-11eb-88f2-0a1b89854a29.PNG)

Design looks good :) Try making more frames. Also, try changing the color palette 🎨
https://dribbble.com/shots/15316388-eLearning-Mobile-App-I-Ofspace

**Comment by deeptea22** [comment]
@awantika10 Actually @garvitraj initially told he was going to do it with Adobe XD, so i immediately started working on it using figma. By the time he switched to figma i was already 70% done with my design. So please take a look at mine and let me know. Thanks :)
https://www.figma.com/file/XsiAbwGmeozKOJQ6my4G4X/Tutoring-App?node-id=0%3A1

**Comment by awantika10** [comment]
@garvitraj @deeptea22 Ping me up in discord

**Comment by deeptea22** [comment]
hey @SHITIZ-AGGARWAL @weebo-ary @awantika10  Please review my design and let me know.
https://www.figma.com/file/XsiAbwGmeozKOJQ6my4G4X/Tutoring-App?node-id=0%3A1

**Comment by hariramjp777** [comment]
Hi, I'd like to design a UI for tutor finding application. Please assign this to me. @awantika10 

My Idea:

* Home page which contains navbar, hero section, reviews about the app and social links
* Sign in and Sign up page for tutors and students
* Logged In state for students
       - list of tutors as cards.
       - If click a tutor card, he'll be taken to a page showing tutor profile and reviews.
       - sign up button to connect with a tutor.
       - Assignments page to show the progress.
       - Chatbox
 * Logged In state for tutors
       - List of enrolled students
       - Given challenges to students
       - Chatbox
 * Edit profile page for both tutors and students

**Comment by SHITIZ-AGGARWAL** [comment]
@hariramjp777 this issue is already assigned
