### ISSUE TITLE
Feat: Make UI for a networking platform for workout enthusiasts (idea-13)

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [awantika10/Desgen#85]
**What is your feature request related to ?**

- [x] Designing

**Description**

Maki ui design for an application for a networking platform for workout enthusiasts
The design should be made using new ui technology trends 
like Glassmorphism , Neumorphism , Retro aesthetic , 3d graphics etc

`Please mention the technology you will be using to solve this issue in comments`

You can use any software you are comfortable with like Figma, AdobeXD , framer etc

**Describe the solution you'd like**

```
Description
A networking platform for workout enthusiasts to find the right workout-partner based on preferences and levels.

Features
 - Profile of the user along with preferences whether they are into dance/yoga/pilates and level, they need not reveal their real names and can just use sudo-names as in game platforms.  
 - Users can find workout partners around the world and them as friends or just follow them.  
 - Customizable workout calendar template every month. 
 - Integration of spotify api or any other music platform to create a customised workout playlist which could collaborative type.  
 - A discussion forum for various workout-type communities.  
 - Individual chat feature for partners to discuss their daily workout regime.  
 - A milestone tracker for every individual to showcase achievements and upgrading to different levels.
 
```
You can also add your features in it

**Additional context**

Please give updates of your work at least once in every 3 days ,else the issue will be assigned to others. 
Before making the final PR please ask first

**Comment by garima010303** [comment]
Sir, Can I work in this using neuromorphism technology via figma? @SHITIZ-AGGARWAL

**Comment by manognyaa** [comment]
can I work on this issue I will be using neuromorphism technology via figma @SHITIZ-AGGARWAL

**Comment by SHITIZ-AGGARWAL** [comment]
@garima010303 @manognyaa assigning you both

**Comment by awantika10** [comment]
Update?

**Comment by manognyaa** [comment]
I have created a profile, chat box, calendar and also 3 onboarding wire frames. @awantika10 It will take only few more days.

**Comment by garima010303** [comment]
I've created login, profile and tracker page. Just few more days I need to complete the remaining ones. I'll upload them soon.

**Comment by manognyaa** [comment]
@awantika10 @SHITIZ-AGGARWAL 
Hello,


I have completed the workout ui design, hope you guys will like it. Please review it and let me know if any changes needed am happy to accept it .

'FIGMA' :https://www.figma.com/proto/QPnTWbbYwBWZ3pdVYS0y1g/gssoc-21?node-id=22%3A218&viewport=-561%2C418%2C0.9755308628082275&scaling=scale-down

**Comment by garima010303** [comment]
Just one more day, it's about to complete. I'll submit it by tomorrow for sure.

**Comment by garima010303** [comment]
I've completed. Sorry for the delay. Should I've to create a pull request? @awantika10 @SHITIZ-AGGARWAL

**Comment by SHITIZ-AGGARWAL** [comment]
@manognyaa The design looks good , please create a pull request asap. 
@garima010303 We asked everyone to get their designs reviewed. If your design is ready please get it reviewed within 2 days or else this issue will be closed due to inactivity.

All the discussion is on discord
