### ISSUE TITLE
Feat: Make UI for "Share if You Care" App (idea-14)

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [awantika10/Desgen#89]
**What is your feature request related to ?**

- [x] Designing

**Description**

Maki ui design for an application : Share if You Care
The design should be made using new ui technology trends 
like Glassmorphism , Neumorphism , Retro aesthetic , 3d graphics etc

`Please mention the technology you will be using to solve this issue in comments`

You can use any software you are comfortable with like Figma, AdobeXD , framer etc

**Describe the solution you'd like**

```
 Description
This is an idea for application "Share if You Care".Most of the times it is not the lack of available resources for the needy
but the lack of right planning and medium to make it reach to the needy people .This application can help connect people who can join hands to organise collection drives for old clothes,blankets ,books ,extra food etc.This will be different from other applications as it would not only have the option for money contribution but things which mostly go wasted , basic necessities which are in overabundance to some and scarce to others .

Features
Login/Signup Page - For all the volunteers.
Works according to the categories people want to donate/contribute.
Prompt for Location access so that people in same locality can join hands together for the cause
Option to Post about any available resource and chat feature for people to communicate
Notification Alert whenever any requiremnet or resource is needed ,so that people who can help can be notified and come forward.
Collaboration feature for reaching out to more people who want to Raise funds and Sponsor for the drives.
```
You can also add your features in it

**Additional context**

Please give updates of your work at least once in every 3 days ,else the issue will be assigned to others. 
Before making the final PR please ask first

**Comment by vaibhavpathak999** [comment]
Hey, @SHITIZ-AGGARWAL can you please assign this issue to me. I would like to work on this issue. I will be using Glassmorphism to implement this design in AdobeXD.

**Comment by lavishabhambri** [comment]
Hey, @SHITIZ-AGGARWAL can you assign this issue to me, please. I want to work on this & will be using Glassmorphism for this.

**Comment by ishika261** [comment]
Hey @SHITIZ-AGGARWAL can you please assign this issue to me. I would like to work on this.

**Comment by srishtij2000** [comment]
Can I work on this issue?

**Comment by SHITIZ-AGGARWAL** [comment]
@vaibhavpathak999 @lavishabhambri If your design is ready, get it reviewed within 2 days or else this issue will be closed.
