### ISSUE TITLE
Update Bio Section 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [awantika10/Desgen#9]
**What is your feature request related to ?**

- [ ] Documentation

**Description**
What is your feature request ? (A description of the feature. Write about the problem or idea you want to refer in this issue.)
I am requesting to update the bio section in About tab this will help users to know more about us !!

**Describe the solution you'd like**
A description of the solution you would suggest if any. (Any suggestions for issue solving)
We can add some more lines to it so that it will be catchy and more attractive to users !!

**Comment by SHITIZ-AGGARWAL** [comment]
We will look into this , thank you for raising the issue

**Comment by rohan-kulkarni-25** [comment]
Please assign it to me if raised

**Comment by SHITIZ-AGGARWAL** [comment]
sure

**Comment by rohan-kulkarni-25** [comment]
👍🏻
