### ISSUE TITLE
Feat: Make UI for a community application (idea-15)

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [awantika10/Desgen#90]
**What is your feature request related to ?**

- [x] Designing

**Description**

Maki ui design for  a community application
The design should be made using new ui technology trends 
like Glassmorphism , Neumorphism , Retro aesthetic , 3d graphics etc

`Please mention the technology you will be using to solve this issue in comments`

You can use any software you are comfortable with like Figma, AdobeXD , framer etc

**Describe the solution you'd like**

```
Description
This is an idea for making a community which helps through the party hassles and troubles.This app will allow users to have a calendar which will allow them to set their dates.It will also provide the details of the nearest banquets and shops which are required for shopping as well as gifts.It will ask the user to create a todo list so that all the work done can be checked.It will have a invite feature which will allow users to connect and recieve the invitation on their messenger for the party.It will have a group system where the close members can access the invitation and todolist while the others invited for the party can not do the same.

Features
Loading page.
Create a registration page.
Login page
Profile of a user containing buttons of adding friends and have calendar and todo feature
Home page which includes the all the features with the feed which suggests banquets and invitations.
todo list page where all the things that need to be done are written
calendar page to set the date of the function and shopping
Messenger page for party comers to chat
map for the location of all the party comers
Explore corner to explore invitations,banquets and people
posting page where users can share their ideas and what they are comfortable with

 
```
You can also add your features in it

**Additional context**

Please give updates of your work at least once in every 3 days ,else the issue will be assigned to others. 
Before making the final PR please ask first

**Comment by vaishnavig20** [comment]
Can I work on this since it was mine idea?

**Comment by subhasmitapradhan** [comment]
it would be great if I could be of any help in this. @vaishnavig20 can I help you in this ? 2brains working together may be a bit better I guess.

**Comment by shreya-gb** [comment]
@subhasmitapradhan I could work with you!

**Comment by kanishkaa24** [comment]
Hello! Can I work on this?
