### ISSUE TITLE
Feat: Make UI for a reservation booking app. (idea-16)

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [awantika10/Desgen#91]
**What is your feature request related to ?**

- [x] Designing

**Description**

Maki ui design for  a reservation booking app.
The design should be made using new ui technology trends 
like Glassmorphism , Neumorphism , Retro aesthetic , 3d graphics etc

`Please mention the technology you will be using to solve this issue in comments`

You can use any software you are comfortable with like Figma, AdobeXD , framer etc

**Describe the solution you'd like**

```
Description
This is an Idea for Application Named Foodie "HAVE A GOOD FOOD!! MAKE YOUR STOMACH & YOURSELF HAPPY!!” This app will allow every one of us to get aware with restaurants nearby. This app will be similar to the movie tickets booking app. This will have the list of restaurants nearby; their ratings, reviews and menu card last but most importantly Vacancy. Anyone can book a table and order food in that restaurant with this app.

Features
Login/Signup Page
List of restaurants nearby
Display distance from your location, menu, vacancy, ratings, reviews.
Book a table and order food.
Show the time in which your food will be available at your table.
 
```
You can also add your features in it

**Additional context**

Please give updates of your work at least once in every 3 days ,else the issue will be assigned to others. 
Before making the final PR please ask first

**Comment by srishtij2000** [comment]
Can I work on this issue?

**Comment by sgautam2503** [comment]
@SHITIZ-AGGARWAL I want to work on this issue. Can you please assign it to me.

**Comment by sgautam2503** [comment]
@SHITIZ-AGGARWAL http://bit.ly/2P9tX48 Review the login and signup page for this

**Comment by sgautam2503** [comment]
[http://bit.ly/2P9tX48](url)

**Comment by awantika10** [comment]
@srishtij2000 @sgautam2503 update?

**Comment by sgautam2503** [comment]
@awantika10 https://www.figma.com/file/GMabDxlzYCRzCCqaYIzbRi/Booking-App?node-id=0%3A1 Review this.

**Comment by awantika10** [comment]
> @awantika10 https://www.figma.com/file/GMabDxlzYCRzCCqaYIzbRi/Booking-App?node-id=0%3A1 Review this.

Hey! Ping me up in discord. Need to make some changes. Overall looks good :)

**Comment by srishtij2000** [comment]
Will submit it by the end of the day

**Comment by kanishkaa24** [comment]
Hello! Can I work on this?

**Comment by kanishkaa24** [comment]
Hello! Can I work on this?
