### ISSUE TITLE
Feat: Make UI for health application (idea-17)

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [awantika10/Desgen#92]
**What is your feature request related to ?**

- [x] Designing

**Description**

Maki ui design for a health application.
The design should be made using new ui technology trends 
like Glassmorphism , Neumorphism , Retro aesthetic , 3d graphics etc

`Please mention the technology you will be using to solve this issue in comments`

You can use any software you are comfortable with like Figma, AdobeXD , framer etc

**Describe the solution you'd like**

```
Description .
This app aims to not only give awareness about mental health but also promote healthy ways to deal with these kind of isssues. 1 daily motivational quote on homepage for positive vibes. A chatbot in it as well which asks a person how they feel about their day at the end of the day. Best food to eat for healty mind eachday. A section for best habits to do in a day eg. sitting in Sun in winters, drinking water, etc and ticking off the checkboxes. Giving a person options if they think they are an overthinker, giving them a reminder to write daily about how they feel. An achievement section to celebrate little achievements.

Features
Login/ signup page.
Cool and calm music going in the bg of app.
Chatbot
Best food recommendations each day
A section for best habits to do in a day
Achievement section
Blogs about mental health 
```
You can also add your features in it

**Additional context**

Please give updates of your work at least once in every 3 days ,else the issue will be assigned to others. 
Before making the final PR please ask first

**Comment by Shweta200126** [comment]
Hey, I'd love to work on this. (I also gave the idea).

**Comment by ishika261** [comment]
hey, i would love to work on this

**Comment by awantika10** [comment]
> hey, i would love to work on this

@ishika261 @Shweta200126 Please do collaborate

**Comment by aditisneh** [comment]
Hey @awantika10 , can I collab with @Shweta200126 @ishika261. Would love to work.

**Comment by awantika10** [comment]
@ishika261 @Shweta200126 Please post your design here

**Comment by aditisneh** [comment]
@awantika10 can I work on this if @ishika261 @Shweta200126 aren't active

**Comment by Shweta200126** [comment]
Hi everyone, I'll start working on this issue starting today. I had my end sem exams going on. If u guys have made some progress, we should definitely share about it.

**Comment by Shweta200126** [comment]
I'm a beginner at this but I want to make this look good, so I'm gonna invest my time in this user research, design. Probably giving the next three days in user research and then taking the time to design. What do you guys think?

**Comment by srishtij2000** [comment]
Can I work on this issue?

**Comment by aditisneh** [comment]
Hey, I want to work on this issue. It has been over a month, the assignees aren't active, So @awantika10 can you assign this to me :)

**Comment by kanishkaa24** [comment]
Hello! Can I work on this?

**Comment by aditisneh** [comment]
@awantika10 do add the level tag if you reviewed the designs, will make a PR
