### ISSUE TITLE
Feat: Maki ui design for an application for pets adoption (idea-18)

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [awantika10/Desgen#93]
**What is your feature request related to ?**

- [x] Designing

**Description**

Maki ui design for an application for pets adoption
The design should be made using new ui technology trends 
like Glassmorphism , Neumorphism , Retro aesthetic , 3d graphics etc

`Please mention the technology you will be using to solve this issue in comments`

You can use any software you are comfortable with like Figma, AdobeXD , framer etc

**Describe the solution you'd like**

```
Description .
An app that can help people find pets that are up for adoption. People can search using different filters like listing out the only options available in their locality or at any particular location or animals of a certain age or breed. You can also upload the details of stray dogs, cats or any other needy animal that you have found or rescued for adoption. This app will make it easier for them to find their forever home and will also help to make a room for another needy animal. It can be named "PetFinds' or 'FindYourPet'.

Features
Login/Signup page.
Explore page that will show all the available post for adoption.
Location, breed and age filter in search
Chat option for communication between adopter and current owner.
Option to add a new adoption post in which we can upload details of the pet and a compulsory image upload option in it.
Option to delete the post from the available adoption posts in which we have to give reason - either 'adopted' or 'other reason'.
It will display total number of adopted pets through this app and update automatically when a pet is marked adopted while taking down the list.
Additionally it can also has a section of successful adoption stories and other informative articles about adoption culture.
```
You can also add your features in it

**Additional context**

Please give updates of your work at least once in every 3 days ,else the issue will be assigned to others. 
Before making the final PR please ask first

**Comment by Bhawna147** [comment]
Can I work on this ?

**Comment by Bhawna147** [comment]
please assign this to me

**Comment by SHITIZ-AGGARWAL** [comment]
Sure

**Comment by Anushka-Rajvanshi** [comment]
I want to work on it along with @Bhawna147. Please assign me this issue.

**Comment by vidhi1121** [comment]
can you assign it to me?

**Comment by Bhawna147** [comment]
@awantika10 @SHITIZ-AGGARWAL here's the ss of my design that i have done so far  please review it and let me know the changes if required. 
https://www.figma.com/file/WBQi8Le1mkfjHLpt8Yzonf/Gssoc?node-id=0%3A1

![image](https://user-images.githubusercontent.com/79100530/111865877-9cdd2780-898f-11eb-8429-cde62e2b79c2.png)

**Comment by awantika10** [comment]
@Bhawna147 Design looks good :) Couple of changes. You need to improve the secondary color. Buttons size can be improved, it's too large.
The purple 🟣 shadows which you have used doesn't match well. Try using a lighter color.
Reference : https://dribbble.com/shots/11996888-Dog-Lovers

**Comment by Anushka-Rajvanshi** [comment]
@awantika10 If two person can be assigned to this issue then please assign me. I would like to work on it.

**Comment by awantika10** [comment]
> @awantika10 If two person can be assigned to this issue then please assign me. I would like to work on it.

Please collaborate with @Bhawna147

**Comment by SKV-programmer** [comment]
I want to collab with @Bhawna147

**Comment by Anushka-Rajvanshi** [comment]
We have made the design for adoption app. Please review it and let us know if it requires any changes. @awantika10  
https://www.figma.com/file/WBQi8Le1mkfjHLpt8Yzonf/find-your-pet-desgen-Gssoc?node-id=0%3A1

**Comment by awantika10** [comment]
@Anushka-Rajvanshi @Bhawna147  Kindly improve these two mockups and you can make the PR

![githunjkenj](https://user-images.githubusercontent.com/71998138/113090231-f1da3280-9206-11eb-8b8c-42e46b368956.PNG)

**Comment by Bhawna147** [comment]
@awantika10 this is our final design we have made all the changes. So can We make a PR now?
https://www.figma.com/file/WBQi8Le1mkfjHLpt8Yzonf/find-your-pet-desgen-Gssoc?node-id=0%3A1

**Comment by SHITIZ-AGGARWAL** [comment]
@Bhawna147 yes! you can

**Comment by SHITIZ-AGGARWAL** [comment]
@Bhawna147 @Anushka-Rajvanshi Read [Design submission](https://github.com/awantika10/Desgen/blob/gssoc/Contribution/CONTRIBUTING.md#design-submission) before making the pull request, if you have any doubt you can clear it on discord.
