### ISSUE TITLE
Contest: Make Ui design for Desgen Website 

### ISSUE THREAD

**Issue by SHITIZ-AGGARWAL** [awantika10/Desgen#94]
## Description
**Create Ui design for Desgen Website**

```
You only have to make designs , no need to code it. 

It will be a static website for now.
It will contain the designs and other information about the platform

``` 

**This is an open contest , so you don't have to get assigned . Do not comment until your design is ready .First you have create design for the whole platform**

**Then Comment on the issue  with the given details**

```
Name : 
Design Link :  
Discord username : "example - shìtìz#7676"
```
**You can work on any software - Figma, AdobeXD, Framer etc**

**Don't create any pull request , You have to only comment on the issue with your design link ( do not add photos in the comment section )**

**Best 3-5 designs will be allowed to make a pull request and will be merged with level-3 label**

**Any doubts or issues will be resolved on discord**

**Comment by Jaagrav** [comment]
I can work on this and send you the figma file link, I can simultaneously code it out as well in React if you need me to.

**Comment by SHITIZ-AGGARWAL** [comment]
> I can work on this and send you the figma file link, I can simultaneously code it out as well in React if you need me to.

This contest is only for designing. The tech stack is not finalised so coding will be seen later. 
Also for doubts please ask on discord , this comment section should only be used for contest design submission (design links)

**Comment by Avnish5** [comment]
Kindly assign this task to me under GSSOC 2021.

**Comment by weebo-ary** [comment]
@Avnish5 You can start the work I have assigned you....

**Comment by Avnish5** [comment]
@weebo-ary Thanku sir to assigning it to me.

**Comment by awantika10** [comment]
@Avnish5  This issue is open to all, hence no assignment required

**Comment by Avnish5** [comment]
@awantika10 okay mam.

**Comment by sowmiyeh** [comment]
Wanted to design a website for Desgen.

**Comment by weebo-ary** [comment]
You can go ahead with this !!

**Comment by awantika10** [comment]
> Wanted to design a website for Desgen.

Sure go ahead

**Comment by jhasuraj01** [comment]
Website Design Submission

Name :  Suraj Jha
Design Link :  https://www.figma.com/file/7r9WAQKLy5HXc0PdMvfi1K/Desgen-Website?node-id=59%3A1008
Discord username : Suraj Jha#7035

**Comment by jhasuraj01** [comment]
> 
> 
> Website Design Submission
> 
> Name : Suraj Jha
> Design Link : https://www.figma.com/file/7r9WAQKLy5HXc0PdMvfi1K/Desgen-Website?node-id=59%3A1008
> Discord username : Suraj Jha#7035

@SHITIZ-AGGARWAL @awantika10 here is my submission (it's not complete due to time constraints)

**Comment by Chadha93** [comment]
Name: Gaurav Chadha
Design Link:  https://www.figma.com/file/ZOqO0LwnZsfcYEQP7dcKp9/website-ui-desgen?node-id=2%3A33
Discord username : Gaurav Chadha(P)#7374

**Comment by vaibhavpathak999** [comment]
Name: Vaibhav Pathak
Design Link:  Adobe XD file 
Discord username: Vaibhav(P)#9231

XD file format is not supported in the comments. So I am attaching my png and I am sending my Adobe XD 
![Web 1920 – 2](https://user-images.githubusercontent.com/51280899/112502146-d5299f00-8daf-11eb-822f-6b193f44e1b9.png)
![Web 1920 – 3](https://user-images.githubusercontent.com/51280899/112502202-e2468e00-8daf-11eb-954e-2248fa7e0d05.png)



file on discord's design discussion channel.

**Comment by sowmiyeh** [comment]
Website Design Submission

Name : Sowmiya V
Design Link : https://www.figma.com/file/ilZao1jeIbY3zh9Ey79g32/Desgen-website?node-id=4%3A14
Prototype link : https://www.figma.com/file/ilZao1jeIbY3zh9Ey79g32/Desgen-website?node-id=29%3A0
Discord username : Sowmiya V#1169

**Comment by Bhawna147** [comment]
Website design
Name - Bhawna khatri
Discord I'd - Bhawna#9241
Link - https://www.figma.com/file/YYFxbDf4Yrp4Z4EY7oqJKw/desgen-web-gssoc?node-id=0%3A1

**Comment by Bhawna147** [comment]
@awantika10 i have made some changes in my site can you please review it also as you said  some of its  element can be used in main website, so can i make a PR?

**Comment by aditi1403** [comment]
Name: Aditi Yadav
Design link: https://www.figma.com/proto/t83EYpNaYZY7GCdtoXFx6O/Desgen?node-id=25%3A0&scaling=min-zoom&page-id=0%3A1
Discord: Aditi Yadav (P)#8862

**Comment by Chadha93** [comment]
@awantika10 @SHITIZ-AGGARWAL @weebo-ary  Also add gssoc21 tag to this issue

**Comment by kunal299** [comment]
Name : Kunal Mali
Design Link :  https://www.figma.com/file/udA9MwccRmjVVx06X8Fsth/Desgen-Website-Design?node-id=0%3A1
Discord username : "Kunal Mali(P)#9230"

**Comment by kunal299** [comment]
@SHITIZ-AGGARWAL @awantika10 Plz review this. If any changes required tell me.

**Comment by kunal299** [comment]
@SHITIZ-AGGARWAL @awantika10 Is this fine?

**Comment by SHITIZ-AGGARWAL** [comment]
@kunal299 @aditi1403 @Bhawna147 @sowmiya-venkatesan @vaibhavpathak999 you all can submit your pull requests

**Comment by rohan-kulkarni-25** [comment]
@SHITIZ-AGGARWAL I will like to work on code section Please let me know when it starts
