### ISSUE TITLE
UPDATE README FILE

### ISSUE THREAD

**Issue by ANSHIKA1806** [awantika10/Desgen#99]
README is the first file one should read when starting a new project. It's a set of useful information about a project, and a kind of manual. A README text file appears in many various places and refers not only to programming. So i want to make your README file more meaningful and more easier to understand the whole project.

**Comment by ANSHIKA1806** [comment]
@awantika10 @weebo-ary @SHITIZ-AGGARWAL @ShauryaBhandari  please assign this task to me ,I am GSSoC'21 participants.
I will do my best to update README file as it is the most important file to know about the project.

**Comment by SHITIZ-AGGARWAL** [comment]
@ANSHIKA1806 please tell what are the changes you will be making in the README in detail , then accordingly we will see if this issue should be allowed or not

**Comment by ANSHIKA1806** [comment]
@SHITIZ-AGGARWAL 
Thanks for responding , I want to add some more  attractive images on README file to make it look better. 
I also want to add some more elements  and modify existing elements like
.Introduction - the project's aim
.Technologies
.Launch
.Table of contents
.Illustrations
.Scope of functionalities 
.Examples of use
.Project status

**Comment by awantika10** [comment]
> @SHITIZ-AGGARWAL
> Thanks for responding , I want to add some more attractive images on README file to make it look better.
> I also want to add some more elements and modify existing elements like
> .Introduction - the project's aim
> .Technologies
> .Launch
> .Table of contents
> .Illustrations
> .Scope of functionalities
> .Examples of use
> .Project status

Okay sure go ahead

**Comment by SHITIZ-AGGARWAL** [comment]
@ANSHIKA1806 any updates on you work ?

**Comment by ANSHIKA1806** [comment]
@SHITIZ-AGGARWAL  
yes, i had made the pull request , please check it and suggest for improvement or accept the pull request.

**Comment by SHITIZ-AGGARWAL** [comment]
@ANSHIKA1806 Thank-you for your contribution . Closing this issue now

**Comment by ANSHIKA1806** [comment]
@SHITIZ-AGGARWAL Thank you so much sir
